name: librecad
version: '2.2.1.2'
grade: stable
base: core22
confinement: strict
license: GPL-2.0
summary: "LibreCAD: 2D open source CAD"
compression: lzo
description: |
  LibreCAD is a cross-platform 2D CAD program written in C++17. It reads DXF/DWG files and writes DXF/PDF/SVG. Supports point/line/circle/ellipse/parabola/spline primitives. UI is customizable with dozens of translations.
  Repo: https://github.com/LibreCAD/LibreCAD

environment:
  LD_LIBRARY_PATH: $SNAP/usr/local/lib/:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/:$SNAP/usr/lib64/:$LD_LIBRARY_PATH
  QT_SELECT: qt5

apps:
  librecad:
    command: usr/bin/librecad
    plugs: [home, desktop, desktop-legacy, opengl, wayland, unity7, x11]
    desktop: usr/share/applications/org.librecad.librecad.desktop
    common-id: org.librecad.librecad.desktop
    extensions: [kde-neon]

plugs:
  desktop:
    mount-host-font-cache: false
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes
  kf5-core22-sdk:
    content: kf5-core22-sdk
    interface: content
    default-provider: kf5-core22-sdk
    target: $SNAP/kf5
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes

parts:
  librecad:
    plugin: qmake
    source: https://github.com/LibreCAD/LibreCAD.git
    source-type: git
    source-tag: v2.2.1.2
    qmake-parameters: ["QMAKE_CFLAGS+=-march=x86-64", "QMAKE_CXXFLAGS+=-march=x86-64"]
    build-environment: [{QT_SELECT: qt5}]
    build-packages:
      - build-essential
      - qtbase5-dev
      - qttools5-dev
      - librsvg2-bin
      - libqt5waylandclient5-dev
      - libfreetype6-dev
      - libicu-dev
      - libqt5opengl5-dev
      - libboost-dev
      - libgl1-mesa-dev
      - libqt5svg5-dev
      - rsync
      - qtchooser
      - qt5-qmake
      - qttools5-dev-tools
      - libmuparser-dev
    override-build: |
      craftctl default
      make -r -j$(nproc)
    stage-packages:
      - libfreetype6
      - libqt5gui5
      - libqt5pdf5
      - libqt5svg5
      - libqt5printsupport5
      - libqt5waylandclient5
      - libmuparser2v5
      - libgl1
    stage: [-usr/share/pkgconfig]
    override-stage: |
      export SRC_DIR=$CRAFT_PART_BUILD/unix
      mkdir -p $CRAFT_STAGE/usr/{bin,share/{icons,librecad/resources/qm,applications}}
      cp -a $SRC_DIR/librecad $CRAFT_STAGE/usr/bin/
      find $CRAFT_PART_SRC/librecad/res $CRAFT_PART_SRC/librecad/ts -name '*.qm' -exec cp -a {} $CRAFT_STAGE/usr/share/librecad/resources/qm/ ';'
      rsync -vaut $CRAFT_PART_SRC/librecad/support/* $CRAFT_STAGE/usr/share/librecad/resources/
      find $CRAFT_PART_SRC -type f -name librecad.svg -exec cp -av '{}' $CRAFT_STAGE/usr/share/icons/ ';'
      export DESKTOP_DIR=$CRAFT_PART_SRC/desktop
      cp -a $DESKTOP_DIR/*.desktop $CRAFT_STAGE/usr/share/applications/org.librecad.librecad.desktop
      sed -i 's:^\s*Icon=.*$:Icon=/usr/share/icons/librecad.svg:' $CRAFT_STAGE/usr/share/applications/org.librecad.librecad.desktop
      cp -a $DESKTOP_DIR/org.librecad.*.xml $CRAFT_STAGE/usr/share/applications/
      craftctl default
    override-prime: |
      rsync -av $CRAFT_STAGE/* ./
      craftctl default
