.TH TTF2LFF 1 "July 2012" "Debian GNU/Linux"
.SH NAME
ttf2lff \- ttf to lff converter.
.SH DESCRIPTION
ttf2lff is a font converter. It convert fonts in ttf format to lff format usseful
to use with LibreCAD or another app that uses this format.

ttf2lff invocation parameters are printed to the console if ttf2lff is called without parameters.
