<!DOCTYPE TS>
<TS language="nl">
<context>
    <name>QObject</name>
    <message>
        <source>None</source>
        <translation>Geen</translation>
    </message>
    <message>
        <source>Inch</source>
        <translation>Inch</translation>
    </message>
    <message>
        <source>Foot</source>
        <translation>Voet</translation>
    </message>
    <message>
        <source>Mile</source>
        <translation>Mile</translation>
    </message>
    <message>
        <source>Millimeter</source>
        <translation>Millimeter</translation>
    </message>
    <message>
        <source>Centimeter</source>
        <translation>Centimeter</translation>
    </message>
    <message>
        <source>Meter</source>
        <translation>Meter</translation>
    </message>
    <message>
        <source>Kilometer</source>
        <translation>Kilometer</translation>
    </message>
    <message>
        <source>Microinch</source>
        <translation>Microinch</translation>
    </message>
    <message>
        <source>Mil</source>
        <translation>Mil</translation>
    </message>
    <message>
        <source>Yard</source>
        <translation>Yard</translation>
    </message>
    <message>
        <source>Angstrom</source>
        <translation>Angstrom</translation>
    </message>
    <message>
        <source>Nanometer</source>
        <translation>Nanometer</translation>
    </message>
    <message>
        <source>Micron</source>
        <translation>Micron</translation>
    </message>
    <message>
        <source>Decimeter</source>
        <translation>Decimeter</translation>
    </message>
    <message>
        <source>Decameter</source>
        <translation>Decameter</translation>
    </message>
    <message>
        <source>Hectometer</source>
        <translation>Hectometer</translation>
    </message>
    <message>
        <source>Gigameter</source>
        <translation>Gigameter</translation>
    </message>
    <message>
        <source>Astro</source>
        <translation>Astro</translation>
    </message>
    <message>
        <source>Lightyear</source>
        <translation>Lichtjaar</translation>
    </message>
    <message>
        <source>Parsec</source>
        <translation>Parsec</translation>
    </message>
</context>
</TS>
