<!DOCTYPE TS><TS>
<context>
    <name>QObject</name>
    <message>
        <source>None</source>
        <translation>Brak</translation>
    </message>
    <message>
        <source>Inch</source>
        <translation>Cal</translation>
    </message>
    <message>
        <source>Foot</source>
        <translation>Stopa</translation>
    </message>
    <message>
        <source>Mile</source>
        <translation>Mila</translation>
    </message>
    <message>
        <source>Millimeter</source>
        <translation>Milimetr</translation>
    </message>
    <message>
        <source>Centimeter</source>
        <translation>Centrymetr</translation>
    </message>
    <message>
        <source>Meter</source>
        <translation>Metr</translation>
    </message>
    <message>
        <source>Kilometer</source>
        <translation>Kilometr</translation>
    </message>
    <message>
        <source>Microinch</source>
        <translation>Mikrocal</translation>
    </message>
    <message>
        <source>Mil</source>
        <translation>Mil</translation>
    </message>
    <message>
        <source>Yard</source>
        <translation>Jard</translation>
    </message>
    <message>
        <source>Angstrom</source>
        <translation>Angstrom</translation>
    </message>
    <message>
        <source>Nanometer</source>
        <translation>Nanometr</translation>
    </message>
    <message>
        <source>Micron</source>
        <translation>Mikron</translation>
    </message>
    <message>
        <source>Decimeter</source>
        <translation>Decymetr</translation>
    </message>
    <message>
        <source>Decameter</source>
        <translation>Dekametr</translation>
    </message>
    <message>
        <source>Hectometer</source>
        <translation>Hektometr</translation>
    </message>
    <message>
        <source>Gigameter</source>
        <translation>Gigametr</translation>
    </message>
    <message>
        <source>Astro</source>
        <translation>Astro</translation>
    </message>
    <message>
        <source>Lightyear</source>
        <translation>Rok świetlny</translation>
    </message>
    <message>
        <source>Parsec</source>
        <translation>Parsek</translation>
    </message>
</context>
</TS>
