<!DOCTYPE TS><TS>
<context>
    <name>QObject</name>
    <message>
        <source>None</source>
        <translation></translation>
    </message>
    <message>
        <source>Inch</source>
        <translation></translation>
    </message>
    <message>
        <source>Foot</source>
        <translation></translation>
    </message>
    <message>
        <source>Mile</source>
        <translation></translation>
    </message>
    <message>
        <source>Millimeter</source>
        <translation></translation>
    </message>
    <message>
        <source>Centimeter</source>
        <translation></translation>
    </message>
    <message>
        <source>Meter</source>
        <translation></translation>
    </message>
    <message>
        <source>Kilometer</source>
        <translation></translation>
    </message>
    <message>
        <source>Microinch</source>
        <translation></translation>
    </message>
    <message>
        <source>Mil</source>
        <translation></translation>
    </message>
    <message>
        <source>Yard</source>
        <translation></translation>
    </message>
    <message>
        <source>Angstrom</source>
        <translation></translation>
    </message>
    <message>
        <source>Nanometer</source>
        <translation></translation>
    </message>
    <message>
        <source>Micron</source>
        <translation></translation>
    </message>
    <message>
        <source>Decimeter</source>
        <translation></translation>
    </message>
    <message>
        <source>Decameter</source>
        <translation></translation>
    </message>
    <message>
        <source>Hectometer</source>
        <translation></translation>
    </message>
    <message>
        <source>Gigameter</source>
        <translation></translation>
    </message>
    <message>
        <source>Astro</source>
        <translation></translation>
    </message>
    <message>
        <source>Lightyear</source>
        <translation></translation>
    </message>
    <message>
        <source>Parsec</source>
        <translation></translation>
    </message>
</context>
</TS>
