# generate-custom-nsh.ps1
# Emit scripts/postprocess-windows/custom.nsh with Qt install paths consumed by nsis-msvc.nsi.
# Usage: .\generate-custom-nsh.ps1 -Architecture AMD64|ARM64 [-OutputPath <path>]

param(
    [Parameter(Mandatory=$true)]
    [ValidateSet("AMD64", "ARM64")]
    [string]$Architecture,

    [Parameter(Mandatory=$false)]
    [string]$OutputPath = "scripts\postprocess-windows\custom.nsh"
)

Write-Host "[INFO] Generating custom.nsh for $Architecture..."

# 1. Locate the Qt arch directory, e.g. D:\a\LibreCAD\Qt\6.9.3\msvc2022_64
#    install-qt-action exports QT_ROOT_DIR / Qt6_DIR pointing at this dir
#    (some action versions set Qt6_DIR to <arch>\lib\cmake\Qt6 — handle both).
$qtArchDir = $null
foreach ($candidate in @($env:QT_ROOT_DIR, $env:Qt6_DIR, $env:Qt5_DIR)) {
    if (-not $candidate) { continue }
    if ($candidate -match '(?i)^(.+)\\lib\\cmake\\Qt[56]\\?$') {
        $candidate = $Matches[1]
    }
    if (Test-Path $candidate) {
        $qtArchDir = (Resolve-Path $candidate).Path
        Write-Host "[INFO] Qt arch dir from env: $qtArchDir"
        break
    }
}

# 2. Probe common locations as fallback
if (-not $qtArchDir) {
    Write-Host "[WARNING] No Qt env var resolved; probing filesystem..."
    $expectedLeaf = if ($Architecture -eq "ARM64") { "msvc2022_arm64" } else { "msvc2022_64" }
    $searchRoots = @("C:\Qt")
    if ($env:GITHUB_WORKSPACE) {
        $searchRoots += (Join-Path $env:GITHUB_WORKSPACE "..\Qt")
    }
    foreach ($root in $searchRoots) {
        if (-not (Test-Path $root)) { continue }
        $found = Get-ChildItem -Path $root -Directory -Recurse -Filter $expectedLeaf -ErrorAction SilentlyContinue |
                 Sort-Object FullName -Descending | Select-Object -First 1
        if ($found) {
            $qtArchDir = $found.FullName
            Write-Host "[INFO] Qt arch dir from probe: $qtArchDir"
            break
        }
    }
}

if (-not $qtArchDir) {
    $qtArchDir = if ($Architecture -eq "ARM64") { "C:\Qt\6.9.0\msvc2022_arm64" } else { "C:\Qt\6.9.0\msvc2022_64" }
    Write-Warning "[WARNING] Falling back to hard-coded path: $qtArchDir"
}

# 3. Decompose <root>\<version>\<archSubdir>
$archSubdir = Split-Path $qtArchDir -Leaf
$versionDir = Split-Path $qtArchDir -Parent
$qtVersion  = Split-Path $versionDir -Leaf
$qtRoot     = Split-Path $versionDir -Parent

if ($qtVersion -notmatch '^\d+\.\d+(\.\d+)?$') {
    Write-Warning "[WARNING] Extracted Qt version '$qtVersion' is unusual"
}

# 4. Per-architecture display names
if ($Architecture -eq "AMD64") {
    $appKeyName = "LibreCADx64"
    $appName    = "LibreCAD (x64)"
    $archSuffix = "_x64"
} else {
    $appKeyName = "LibreCADARM64"
    $appName    = "LibreCAD (ARM64)"
    $archSuffix = "_arm64"
}

Write-Host "[INFO] Qt root        : $qtRoot"
Write-Host "[INFO] Qt version     : $qtVersion"
Write-Host "[INFO] Qt arch subdir : $archSubdir"

# 5. Emit custom.nsh — defines consumed by nsis-msvc.nsi
$lines = @(
    "; Auto-generated by scripts/generate-custom-nsh.ps1 - do not edit by hand"
    "; Architecture: $Architecture"
    ""
    "!define Qt_Dir       `"$qtRoot`""
    "!define Qt_Version   `"$qtVersion`""
    "!define MSVC_Ver     `"$archSubdir`""
    "!define InstallerName `"LibreCAD-Installer`""
    "!define ProgramsFolder `"`$PROGRAMFILES64`""
    "!define AppKeyName   `"$appKeyName`""
    "!define AppName      `"$appName`""
    ""
)
$nshContent = ($lines -join "`r`n")

$outputDir = Split-Path $OutputPath -Parent
if ($outputDir -and -not (Test-Path $outputDir)) {
    New-Item -ItemType Directory -Force -Path $outputDir | Out-Null
}

# ASCII keeps NSIS happy across versions (no BOM, plain text)
[System.IO.File]::WriteAllText((Resolve-Path -LiteralPath (Split-Path $OutputPath -Parent)).Path + "\" + (Split-Path $OutputPath -Leaf), $nshContent, [System.Text.Encoding]::ASCII)

Write-Host "[SUCCESS] Wrote $OutputPath"
Write-Host "---- contents ----"
Write-Host $nshContent
