#!/usr/bin/env python3
import os
import re
import sys

LANGUAGE_FALLBACKS = {
    'es_ar': 'es', 'es_bo': 'es', 'es_cl': 'es', 'es_co': 'es', 'es_cr': 'es',
    'es_do': 'es', 'es_ec': 'es', 'es_gt': 'es', 'es_hn': 'es', 'es_mx': 'es',
    'es_ni': 'es', 'es_pa': 'es', 'es_pe': 'es', 'es_pr': 'es', 'es_py': 'es',
    'es_sv': 'es', 'es_us': 'es', 'es_uy': 'es', 'es_ve': 'es',
    'pt_br': 'pt_pt',
    'sr_ba': 'sr', 'sr_me': 'sr', 'sr_rs': 'sr',
    'en_au': 'en',
}

TRANSLATIONS = {
    "+": {
        "zh_cn": "+", "zh_tw": "+", "de": "+", "fr": "+", "es": "+",
        "ru": "+", "ja": "+", "ko": "+", "it": "+", "pt_pt": "+",
        "nl": "+", "pl": "+", "hu": "+", "cs": "+", "da": "+",
        "sv": "+", "fi": "+", "no": "+", "tr": "+", "el": "+",
        "he": "+", "id_id": "+", "th": "+", "ar": "+", "ca": "+",
        "eu": "+", "gl": "+", "hi": "+", "ka": "+", "mk": "+",
        "pa": "+", "ro_ro": "+", "sk": "+", "sl": "+", "sq_al": "+",
        "sr": "+", "ta": "+", "uk": "+", "et": "+", "lv": "+",
    },
    "-": {
        "zh_cn": "-", "zh_tw": "-", "de": "-", "fr": "-", "es": "-",
        "ru": "-", "ja": "-", "ko": "-", "it": "-", "pt_pt": "-",
        "nl": "-", "pl": "-", "hu": "-", "cs": "-", "da": "-",
        "sv": "-", "fi": "-", "no": "-", "tr": "-", "el": "-",
        "he": "-", "id_id": "-", "th": "-", "ar": "-", "ca": "-",
        "eu": "-", "gl": "-", "hi": "-", "ka": "-", "mk": "-",
        "pa": "-", "ro_ro": "-", "sk": "-", "sl": "-", "sq_al": "-",
        "sr": "-", "ta": "-", "uk": "-", "et": "-", "lv": "-",
    },
    "->": {
        "zh_cn": "->", "zh_tw": "->", "de": "->", "fr": "->", "es": "->",
        "ru": "->", "ja": "->", "ko": "->", "it": "->", "pt_pt": "->",
        "nl": "->", "pl": "->", "hu": "->", "cs": "->", "da": "->",
        "sv": "->", "fi": "->", "no": "->", "tr": "->", "el": "->",
        "he": "->", "id_id": "->", "th": "->", "ar": "->", "ca": "->",
        "eu": "->", "gl": "->", "hi": "->", "ka": "->", "mk": "->",
        "pa": "->", "ro_ro": "->", "sk": "->", "sl": "->", "sq_al": "->",
        "sr": "->", "ta": "->", "uk": "->", "et": "->", "lv": "->",
    },
    "&lt;-": {
        "zh_cn": "<-", "zh_tw": "<-", "de": "<-", "fr": "<-", "es": "<-",
        "ru": "<-", "ja": "<-", "ko": "<-", "it": "<-", "pt_pt": "<-",
        "nl": "<-", "pl": "<-", "hu": "<-", "cs": "<-", "da": "<-",
        "sv": "<-", "fi": "<-", "no": "<-", "tr": "<-", "el": "<-",
        "he": "<-", "id_id": "<-", "th": "<-", "ar": "<-", "ca": "<-",
        "eu": "<-", "gl": "<-", "hi": "<-", "ka": "<-", "mk": "<-",
        "pa": "<-", "ro_ro": "<-", "sk": "<-", "sl": "<-", "sq_al": "<-",
        "sr": "<-", "ta": "<-", "uk": "<-", "et": "<-", "lv": "<-",
    },
    "-&gt;": {
        "zh_cn": "->", "zh_tw": "->", "de": "->", "fr": "->", "es": "->",
        "ru": "->", "ja": "->", "ko": "->", "it": "->", "pt_pt": "->",
        "nl": "->", "pl": "->", "hu": "->", "cs": "->", "da": "->",
        "sv": "->", "fi": "->", "no": "->", "tr": "->", "el": "->",
        "he": "->", "id_id": "->", "th": "->", "ar": "->", "ca": "->",
        "eu": "->", "gl": "->", "hi": "->", "ka": "->", "mk": "->",
        "pa": "->", "ro_ro": "->", "sk": "->", "sl": "->", "sq_al": "->",
        "sr": "->", "ta": "->", "uk": "->", "et": "->", "lv": "->",
    },
    "&lt;-": {
        "zh_cn": "<-", "zh_tw": "<-", "de": "<-", "fr": "<-", "es": "<-",
        "ru": "<-", "ja": "<-", "ko": "<-", "it": "<-", "pt_pt": "<-",
        "nl": "<-", "pl": "<-", "hu": "<-", "cs": "<-", "da": "<-",
        "sv": "<-", "fi": "<-", "no": "<-", "tr": "<-", "el": "<-",
        "he": "<-", "id_id": "<-", "th": "<-", "ar": "<-", "ca": "<-",
        "eu": "<-", "gl": "<-", "hi": "<-", "ka": "<-", "mk": "<-",
        "pa": "<-", "ro_ro": "<-", "sk": "<-", "sl": "<-", "sq_al": "<-",
        "sr": "<-", "ta": "<-", "uk": "<-", "et": "<-", "lv": "<-",
    },
    "input a name and then press +": {
        "zh_cn": "输入名称然后按 +", "zh_tw": "輸入名稱然後按 +",
        "de": "Geben Sie einen Namen ein und drücken Sie dann +",
        "fr": "Entrez un nom puis appuyez sur +",
        "es": "Ingrese un nombre y luego presione +",
        "ru": "Введите имя и нажмите +",
        "ja": "名前を入力して+を押してください",
        "ko": "이름을 입력한 후 +를 누르세요",
        "it": "Inserire un nome e premere +",
        "pt_pt": "Insira um nome e pressione +",
        "nl": "Voer een naam in en druk op +",
        "pl": "Wprowadź nazwę i naciśnij +",
        "hu": "Adjon meg egy nevet, majd nyomjon +",
        "cs": "Zadejte název a stiskněte +",
        "da": "Indtast et navn og tryk +",
        "sv": "Ange ett namn och tryck +",
        "fi": "Syötä nimi ja paina +",
        "no": "Angi et navn og trykk +",
        "tr": "Bir isim girin ve + tuşuna basın",
        "el": "Δώστε ένα όνομα και πατήστε +",
        "he": "הכנס שם ולחץ על +",
        "id_id": "Masukkan nama dan tekan +",
        "th": "ป้อนชื่อแล้วกด +",
        "ar": "أدخل اسمًا ثم اضغط +",
        "ca": "Introduïu un nom i premeu +",
        "eu": "Sartu izen bat eta egin +",
        "gl": "Introduza un nome e prema +",
        "hi": "नाम दर्ज करें और फिर + दबाएं",
        "ka": "შეიყვანეთ სახელი და დააჭირეთ +",
        "mk": "Внесете име и притиснете +",
        "pa": "नाम दर्ज करें और फिर + दबाएं",
        "ro_ro": "Introduceți un nume și apăsați +",
        "sk": "Zadajte názov a stlačte +",
        "sl": "Vnesite ime in pritisnite +",
        "sq_al": "Shtypni një emër dhe pastaj shtypni +",
        "sr": "Унесите име и притисните +",
        "ta": "பெயரை உள்ளிட்டு + அழுத்தவும்",
        "uk": "Введіть назву і натисніть +",
        "et": "Sisestage nimi ja vajutage +",
        "lv": "Ievadiet nosaukumu un nospiediet +",
    },
    "Add or Remove Action": {
        "zh_cn": "添加或删除操作", "zh_tw": "新增或刪除操作",
        "de": "Aktion hinzufügen oder entfernen",
        "fr": "Ajouter ou supprimer une action",
        "es": "Agregar o quitar acción",
        "ru": "Добавить или удалить действие",
        "ja": "アクションの追加または削除",
        "ko": "액션 추가 또는 제거",
        "it": "Aggiungi o rimuovi azione",
        "pt_pt": "Adicionar ou remover ação",
        "nl": "Actie toevoegen of verwijderen",
        "pl": "Dodaj lub usuń akcję",
        "hu": "Művelet hozzáadása vagy eltávolítása",
        "cs": "Přidat nebo odebrat akci",
        "da": "Tilføj eller fjern handling",
        "sv": "Lägg till eller ta bort åtgärd",
        "fi": "Lisää tai poista toiminto",
        "no": "Legg til eller fjern handling",
        "tr": "Eylem Ekle veya Kaldır",
        "el": "Προσθήκη ή Αφαίρεση Δράσης",
        "he": "הוסף או הסר פעולה",
        "id_id": "Tambah atau Hapus Aksi",
        "th": "เพิ่มหรือลบการกระทำ",
        "ar": "إضافة أو إزالة إجراء",
        "ca": "Afegir o eliminar acció",
        "eu": "Gehitu edo kendu ekintza",
        "gl": "Engadir ou eliminar acción",
        "hi": "क्रिया जोड़ें या हटाएं",
        "ka": "დამატება ან წაშლა ქმედება",
        "mk": "Додадете или избришете Акција",
        "pa": "ਐਕਸ਼ਨ ਜੋੜੋ ਜਾਂ ਹਟਾਓ",
        "ro_ro": "Adăugați sau eliminați acțiunea",
        "sk": "Pridať alebo odstrániť akciu",
        "sl": "Dodaj ali odstrani akcijo",
        "sq_al": "Shtoni ose largoni veprim",
        "sr": "Додajte или избришите Акцију",
        "ta": "செயல் சேர்க்கவும் அல்லது நீக்கவும்",
        "uk": "Додати або видалити дію",
        "et": "Lisa või eemalda tegevus",
        "lv": "Pievienot vai izņemt darbību",
    },
    "Drawing Variables": {
        "zh_cn": "绘图变量", "zh_tw": "繪圖變數",
        "de": "Zeichnungsvariablen", "fr": "Variables de dessin",
        "es": "Variables de dibujo", "ru": "Переменные чертежа",
        "ja": "図面変数", "ko": "도면 변수", "it": "Variabili disegno",
        "pt_pt": "Variáveis de desenho", "nl": "Tekenvariabelen",
        "pl": "Zmienne rysunku", "hu": "Rajzváltozók", "cs": "Proměnné výkresu",
        "da": "Tegnevariable", "sv": "Ritvariabler", "fi": "Piirtovaiheet",
        "no": "Tegnevariable", "tr": "Çizim Değişkenleri",
        "el": "Μεταβλητές Σχεδίου", "he": "משתני ציור",
        "id_id": "Variabel Gambar", "th": "ตัวแปรการวาด",
        "ar": "متغيرات الرسم", "ca": "Variables de dibuix",
        "eu": "Marrazki aldagaiak", "gl": "Variables de deseño",
        "hi": "चित्रण चर", "ka": "ჩარჩოს ცვლადები",
        "mk": "Променливи на цртеж", "pa": "ਡਰਾਇੰਗ ਵੇਰੀਏਬਲਜ਼",
        "ro_ro": "Variabile de desen", "sk": "Premenné výkresu",
        "sl": "Spremenljivke risbe", "sq_al": "Variabla e Figurës",
        "sr": "Променљиве цртежа", "ta": "வரைபட மாறிகள்",
        "uk": "Змінні малюнка", "et": "Joonistusmuutujad",
        "lv": "Zīmēšanas mainīgie",
    },
    "Variable": {
        "zh_cn": "变量", "zh_tw": "變數", "de": "Variable", "fr": "Variable",
        "es": "Variable", "ru": "Переменная", "ja": "変数", "ko": "변수",
        "it": "Variabile", "pt_pt": "Variável", "nl": "Variabele",
        "pl": "Zmienna", "hu": "Változó", "cs": "Proměnná", "da": "Variabel",
        "sv": "Variabel", "fi": "Muuttuja", "no": "Variabel", "tr": "Değişken",
        "el": "Μεταβλητή", "he": "משתנה", "id_id": "Variabel", "th": "ตัวแปร",
        "ar": "متغير", "ca": "Variable", "eu": "Aldagaia", "gl": "Variable",
        "hi": "चर", "ka": "ცვლადი", "mk": "Променлива", "pa": "ਵੇਰੀਏਬਲ",
        "ro_ro": "Variabilă", "sk": "Premenná", "sl": "Spremenljivka",
        "sq_al": "Variabël", "sr": "Променљива", "ta": "மாறி",
        "uk": "Змінна", "et": "Muutuja", "lv": "Mainīgais",
    },
    "Code": {
        "zh_cn": "代码", "zh_tw": "代碼", "de": "Code", "fr": "Code",
        "es": "Código", "ru": "Код", "ja": "コード", "ko": "코드",
        "it": "Codice", "pt_pt": "Código", "nl": "Code", "pl": "Kod",
        "hu": "Kód", "cs": "Kód", "da": "Kode", "sv": "Kod", "fi": "Koodi",
        "no": "Kode", "tr": "Kod", "el": "Κωδικός", "he": "קוד",
        "id_id": "Kode", "th": "โค้ด", "ar": "كود", "ca": "Codi",
        "eu": "Kodea", "gl": "Código", "hi": "कोड", "ka": "კოდი",
        "mk": "Код", "pa": "ਕੋਡ", "ro_ro": "Cod", "sk": "Kód",
        "sl": "Koda", "sq_al": "Kodi", "sr": "Код", "ta": "குறியீடு",
        "uk": "Код", "et": "Kood", "lv": "Kods",
    },
    "Value": {
        "zh_cn": "值", "zh_tw": "值", "de": "Wert", "fr": "Valeur",
        "es": "Valor", "ru": "Значение", "ja": "値", "ko": "값",
        "it": "Valore", "pt_pt": "Valor", "nl": "Waarde", "pl": "Wartość",
        "hu": "Érték", "cs": "Hodnota", "da": "Værdi", "sv": "Värde",
        "fi": "Arvo", "no": "Verdi", "tr": "Değer", "el": "Τιμή",
        "he": "ערך", "id_id": "Nilai", "th": "ค่า", "ar": "قيمة",
        "ca": "Valor", "eu": "Balioa", "gl": "Valor", "hi": "मान",
        "ka": "მნიშვნელობა", "mk": "Вредност", "pa": "ਮੁੱਲ",
        "ro_ro": "Valoare", "sk": "Hodnota", "sl": "Vrednost",
        "sq_al": "Vlera", "sr": "Вредност", "ta": "மதிப்பு",
        "uk": "Значення", "et": "Väärtus", "lv": "Vērtība",
    },
    "&OK": {
        "zh_cn": "确定", "zh_tw": "確定", "de": "&OK", "fr": "&OK",
        "es": "&OK", "ru": "&OK", "ja": "&OK", "ko": "&OK",
        "it": "&OK", "pt_pt": "&OK", "nl": "&OK", "pl": "&OK",
        "hu": "&OK", "cs": "&OK", "da": "&OK", "sv": "&OK", "fi": "&OK",
        "no": "&OK", "tr": "&OK", "el": "&OK", "he": "&OK",
        "id_id": "&OK", "th": "&OK", "ar": "&OK", "ca": "&OK",
        "eu": "&OK", "gl": "&OK", "hi": "&OK", "ka": "&OK",
        "mk": "&OK", "pa": "&OK", "ro_ro": "&OK", "sk": "&OK",
        "sl": "&OK", "sq_al": "&OK", "sr": "&OK", "ta": "&OK",
        "uk": "&OK", "et": "&OK", "lv": "&OK",
    },
    "Alt+O": {
        "zh_cn": "Alt+O", "zh_tw": "Alt+O", "de": "Alt+O", "fr": "Alt+O",
        "es": "Alt+O", "ru": "Alt+O", "ja": "Alt+O", "ko": "Alt+O",
        "it": "Alt+O", "pt_pt": "Alt+O", "nl": "Alt+O", "pl": "Alt+O",
        "hu": "Alt+O", "cs": "Alt+O", "da": "Alt+O", "sv": "Alt+O",
        "fi": "Alt+O", "no": "Alt+O", "tr": "Alt+O", "el": "Alt+O",
        "he": "Alt+O", "id_id": "Alt+O", "th": "Alt+O", "ar": "Alt+O",
        "ca": "Alt+O", "eu": "Alt+O", "gl": "Alt+O", "hi": "Alt+O",
        "ka": "Alt+O", "mk": "Alt+O", "pa": "Alt+O", "ro_ro": "Alt+O",
        "sk": "Alt+O", "sl": "Alt+O", "sq_al": "Alt+O", "sr": "Alt+O",
        "ta": "Alt+O", "uk": "Alt+O", "et": "Alt+O", "lv": "Alt+O",
    },
    "Cancel": {
        "zh_cn": "取消", "zh_tw": "取消", "de": "Abbrechen", "fr": "Annuler",
        "es": "Cancelar", "ru": "Отмена", "ja": "キャンセル", "ko": "취소",
        "it": "Annulla", "pt_pt": "Cancelar", "nl": "Annuleren",
        "pl": "Anuluj", "hu": "Mégse", "cs": "Zrušit", "da": "Annuller",
        "sv": "Avbryt", "fi": "Peruuta", "no": "Avbryt", "tr": "İptal",
        "el": "Ακύρωση", "he": "בטל", "id_id": "Batal", "th": "ยกเลิก",
        "ar": "إلغاء", "ca": "Cancel·lar", "eu": "Utzi", "gl": "Cancelar",
        "hi": "रद्द करें", "ka": "გაუქმება", "mk": "Откажи",
        "pa": "ਰੱਦ ਕਰੋ", "ro_ro": "Anulează", "sk": "Zrušiť",
        "sl": "Prekliči", "sq_al": "Anulo", "sr": "Откажи",
        "ta": "திரும்பப் பெற", "uk": "Відміна", "et": "Loobu",
        "lv": "Atcelt",
    },
    "Esc": {
        "zh_cn": "Esc", "zh_tw": "Esc", "de": "Esc", "fr": "Échap",
        "es": "Esc", "ru": "Esc", "ja": "Esc", "ko": "Esc",
        "it": "Esc", "pt_pt": "Esc", "nl": "Esc", "pl": "Esc",
        "hu": "Esc", "cs": "Esc", "da": "Esc", "sv": "Esc", "fi": "Esc",
        "no": "Esc", "tr": "Esc", "el": "Esc", "he": "Esc",
        "id_id": "Esc", "th": "Esc", "ar": "Esc", "ca": "Esc",
        "eu": "Esc", "gl": "Esc", "hi": "Esc", "ka": "Esc",
        "mk": "Esc", "pa": "Esc", "ro_ro": "Esc", "sk": "Esc",
        "sl": "Esc", "sq_al": "Esc", "sr": "Esc", "ta": "Esc",
        "uk": "Esc", "et": "Esc", "lv": "Esc",
    },
    "MakerCAM as of November 2014 does not hide SVG content \nthat has been set invisibe (&quot;display: none&quot; or &quot;visibility: hidden&quot;).": {
        "zh_cn": "截至2014年11月，MakerCAM不会隐藏已设置为不可见的SVG内容（\"display: none\"或\"visibility: hidden\"）。",
        "zh_tw": "截至2014年11月，MakerCAM不會隱藏已設定為不可見的SVG內容（\"display: none\"或\"visibility: hidden\"）。",
        "de": "MakerCAM ab November 2014 blendet SVG-Inhalte nicht aus, die als unsichtbar eingestellt wurden (\"display: none\" oder \"visibility: hidden\").",
        "fr": "MakerCAM depuis novembre 2014 ne masque pas le contenu SVG défini comme invisible (\"display: none\" ou \"visibility: hidden\").",
        "es": "MakerCAM a partir de noviembre de 2014 no oculta el contenido SVG que ha sido configurado como invisible (\"display: none\" o \"visibility: hidden\").",
        "ru": "MakerCAM с ноября 2014 года не скрывает SVG-контент, установленный как невидимый (\"display: none\" или \"visibility: hidden\").",
        "ja": "2014年11月現在、MakerCAMは非表示に設定されたSVGコンテンツ（\"display: none\"または\"visibility: hidden\"）を隠しません。",
        "ko": "2014년 11월 현재 MakerCAM은 보이지 않도록 설정된 SVG 콘텐츠(\"display: none\" 또는 \"visibility: hidden\")를 숨기지 않습니다.",
        "it": "MakerCAM a novembre 2014 non nasconde il contenuto SVG impostato come invisibile (\"display: none\" o \"visibility: hidden\").",
        "pt_pt": "MakerCAM a partir de novembro de 2014 não oculta o conteúdo SVG definido como invisível (\"display: none\" ou \"visibility: hidden\").",
        "nl": "MakerCAM vanaf november 2014 verbergt SVG-inhoud niet die is ingesteld als onzichtbaar (\"display: none\" of \"visibility: hidden\").",
        "pl": "MakerCAM od listopada 2014 roku nie ukrywa zawartości SVG ustawionej jako niewidoczna (\"display: none\" lub \"visibility: hidden\").",
        "hu": "A MakerCAM november 2014 óta nem rejti el az SVG-tartalmakat, amelyek láthatatlannak lettek beállítva (\"display: none\" vagy \"visibility: hidden\").",
        "cs": "MakerCAM od listopadu 2014 nezamýlvá SVG obsah, který byl nastaven jako neviditelný (\"display: none\" nebo \"visibility: hidden\").",
        "da": "MakerCAM fra november 2014 skjuler ikke SVG-indhold, der er blevet indstillet til usynlig (\"display: none\" eller \"visibility: hidden\").",
        "sv": "MakerCAM från november 2014 döljer inte SVG-innehåll som har ställts in som osynligt (\"display: none\" eller \"visibility: hidden\").",
        "fi": "MakerCAM marraskuusta 2014 eteenpäin ei piilota näkymättömäksi asetettua SVG-sisältöä (\"display: none\" tai \"visibility: hidden\").",
        "no": "MakerCAM fra november 2014 skjuler ikke SVG-innhold som er satt til usynlig (\"display: none\" eller \"visibility: hidden\").",
        "tr": "Kasım 2014 itibarıyla MakerCAM, görünmez olarak ayarlanmış SVG içeriğini (\"display: none\" veya \"visibility: hidden\") gizlemez.",
        "el": "Η MakerCAM από τον Νοέμβριο του 2014 δεν κρύβει περιεχόμενο SVG που έχει οριστεί ως μη ορατό (\"display: none\" ή \"visibility: hidden\").",
        "he": "MakerCAM מנובמבר 2014 אינו מסתיר תוכן SVG שהגדר כלא נראה (\"display: none\" או \"visibility: hidden\").",
        "id_id": "MakerCAM sejak November 2014 tidak menyembunyikan konten SVG yang telah diatur sebagai tidak terlihat (\"display: none\" atau \"visibility: hidden\").",
        "th": "MakerCAM ตั้งแต่พฤศจิกายน 2014 ไม่ซ่อนเนื้อหา SVG ที่ตั้งค่าเป็นไม่ปรากฏ (\"display: none\" หรือ \"visibility: hidden\")",
        "ar": "MakerCAM منذ نوفمبر 2014 لا يخفي محتوى SVG الذي تم تعيينه على أنه غير مرئي (\"display: none\" أو \"visibility: hidden\").",
        "ca": "MakerCAM des de novembre de 2014 no oculta el contingut SVG que s'ha configurat com invisible (\"display: none\" o \"visibility: hidden\").",
        "eu": "MakerCAMek 2014ko azaroaz geroago ez du ezkutatu ikusgai ez bezala ezarri den SVG edukia (\"display: none\" edo \"visibility: hidden\").",
        "gl": "MakerCAM dende novembro de 2014 non oculta o contido SVG que se configurou como invisible (\"display: none\" ou \"visibility: hidden\").",
        "hi": "नवंबर 2014 तक का MakerCAM अदृश्य सेट किए गए SVG सामग्री को छिपाता नहीं है (\"display: none\" या \"visibility: hidden\"।",
        "ka": "2014 წლის ნოემბრის შემდეგ MakerCAM-ը არ აგდებს SVG შინაარსს, რომელიც დამალულია (\"display: none\" ან \"visibility: hidden\").",
        "mk": "MakerCAM од ноември 2014 година не го крие SVG содржината која е поставена како невидлива (\"display: none\" или \"visibility: hidden\").",
        "pa": "ਨਵੰਬਰ 2014 ਤੱਕ ਦਾ MakerCAM ਅਦ੍ਰਿਸ਼ਟ ਸੈਟ ਕੀਤੀ SVG ਸਮਗਰੀ ਨੂੰ ਛੁਪਾਉਂਦਾ ਨਹੀਂ ਹੈ (\"display: none\" ਜਾਂ \"visibility: hidden\").",
        "ro_ro": "MakerCAM din noiembrie 2014 nu ascunde conținutul SVG care a fost setat ca invizibil (\"display: none\" sau \"visibility: hidden\").",
        "sk": "MakerCAM od novembra 2014 nezamýlvá SVG obsah, ktorý bol nastavený ako neviditeľný (\"display: none\" alebo \"visibility: hidden\").",
        "sl": "MakerCAM od novembra 2014 ne skriva SVG vsebine, ki je bila nastavljena kot nevidna (\"display: none\" ali \"visibility: hidden\").",
        "sq_al": "MakerCAM që nga nëntori 2014 nuk e fsheh përmbajtjen SVG që është caktuar si e padukshme (\"display: none\" ose \"visibility: hidden\").",
        "sr": "MakerCAM od novembra 2014. godine ne sakriva SVG sadržaj koji je postavljen kao nevidljiv (\"display: none\" ili \"visibility: hidden\").",
        "ta": "நவம்பர் 2014 முதல் MakerCAM பார்வைக்கு இல்லை என்று அமைக்கப்பட்ட SVG உள்ளடக்கத்தை மறைக்காது (\"display: none\" அல்லது \"visibility: hidden\").",
        "uk": "MakerCAM з листопада 2014 року не приховує SVG-контент, налаштований як невидимий (\"display: none\" або \"visibility: hidden\").",
        "et": "MakerCAM alates november 2014 ei pea peita SVG-sisu, mis on määratud nähtamatuks (\"display: none\" või \"visibility: hidden\").",
        "lv": "MakerCAM no novembra 2014 neslēpj SVG saturu, kas ir iestatīts kā neredzams (\"display: none\" vai \"visibility: hidden\").",
    },
    "Exported images can be useful in SVG editors (Inkscape, etc), \nbut avoided in some CAM&apos;s.": {
        "zh_cn": "导出的图像在SVG编辑器（如Inkscape等）中可能有用，但在某些CAM软件中应避免使用。",
        "zh_tw": "匯出的圖像在SVG編輯器（如Inkscape等）中可能有用，但在某些CAM軟體中應避免使用。",
        "de": "Exportierte Bilder können in SVG-Editoren (Inkscape etc.) nützlich sein, sollten aber in einigen CAM-Programmen vermieden werden.",
        "fr": "Les images exportées peuvent être utiles dans les éditeurs SVG (Inkscape, etc.), mais doivent être évitées dans certaines CAM.",
        "es": "Las imágenes exportadas pueden ser útiles en editores SVG (Inkscape, etc.), pero deben evitarse en algunas CAM.",
        "ru": "Экспортированные изображения могут быть полезны в SVG-редакторах (Inkscape и т.д.), но должны быть избежаны в некоторых CAM.",
        "ja": "エクスポートされた画像はSVGエディタ（Inkscapeなど）で役立つ場合がありますが、一部のCAMでは避ける必要があります。",
        "ko": "내보낸 이미지는 SVG 편집기(Inkscape 등)에서 유용할 수 있지만, 일부 CAM에서는 피해야 합니다.",
        "it": "Le immagini esportate possono essere utili negli editor SVG (Inkscape, ecc.), ma devono essere evitate in alcune CAM.",
        "pt_pt": "As imagens exportadas podem ser úteis em editores SVG (Inkscape, etc.), mas devem ser evitadas em algumas CAM.",
        "nl": "Geëxporteerde afbeeldingen kunnen nuttig zijn in SVG-editors (Inkscape, etc.), maar moeten worden vermeden in sommige CAM's.",
        "pl": "Wyeksportowane obrazy mogą być przydatne w edytorach SVG (Inkscape itp.), ale powinny być unikać w niektórych programach CAM.",
        "hu": "Az exportált képek hasznosak lehetnek SVG-szerkesztőkben (Inkscape stb.), de egyes CAM-programokban elkerülendők.",
        "cs": "Exportované obrázky mohou být užitečné v SVG editorech (Inkscape atd.), ale by se měly vyhýbat v některých programech CAM.",
        "da": "Exporterede billeder kan være nyttige i SVG-redigerede (Inkscape, etc.), men skal undgås i nogle CAM's.",
        "sv": "Exporterade bilder kan vara användbara i SVG-redigerare (Inkscape, etc.), men bör undvikas i vissa CAM-program.",
        "fi": "Viedyt kuvat voivat olla hyödyllisiä SVG-editoreissä (Inkscape jne.), mutta niitä tulee välttää joissakin CAM-ohjelmissa.",
        "no": "Eksporterte bilder kan være nyttige i SVG-redigerere (Inkscape, etc.), men bør unngås i noen CAM-programmer.",
        "tr": "Dışa aktarılan görüntüler SVG editörlerinde (Inkscape vb.) faydalı olabilir, ancak bazı CAM'larda kaçınılmalıdır.",
        "el": "Οι εξάγουμενες εικόνες μπορούν να είναι χρήσιμες σε επεξεργαστές SVG (Inkscape κλπ.), αλλά πρέπει να αποφεύγονται σε ορισμένες CAM.",
        "he": "תמונות מיוצאות יכולות להיות שימושיות בעורכים SVG (Inkscape וכו'), אך צריך להימנע מהן בחלק מהמערכות CAM.",
        "id_id": "Gambar yang diekspor dapat berguna di editor SVG (Inkscape, dll.), tetapi harus dihindari di beberapa CAM.",
        "th": "รูปภาพที่ส่งออกสามารถเป็นประโยชน์ในตัวแก้ไข SVG (Inkscape ฯลฯ) แต่ควรหลีกเลี่ยงใน CAM บางตัว",
        "ar": "الصور المصدرة يمكن أن تكون مفيدة في محرر SVG (Inkscape، إلخ)، ولكن يجب تجنبها في بعض برامج CAM.",
        "ca": "Les imatges exportades poden ser útils en editors SVG (Inkscape, etc.), però s'han d'evitar en algunes CAM.",
        "eu": "Esportatutako irudiak SVG-editoreetan (Inkscape etab.) baliagarriak izan daitezke, baina batzuketan CAMetan ekidite behar dira.",
        "gl": "As imaxes exportadas poden ser útiles en editores SVG (Inkscape, etc.), pero deben evitase nalgúns CAM.",
        "hi": "निर्यात की गई छवियां SVG संपादकों (Inkscape, आदि) में उपयोगी हो सकती हैं, लेकिन कुछ CAM में से बचना चाहिए।",
        "ka": "ექსპორტირებული სურათები SVG რედაქტორებში (Inkscape და ა.შ.) სასარგებლო olabilir, მაგრამ ზოგიერთ CAM–ში უნდა თავიდან აცილდეს.",
        "mk": "Експортираните слики може да бидат корисно во SVG уредувачи (Inkscape, итн.), но треба да се избегнуваат во некои CAM програми.",
        "pa": "ਨਿਰਯਾਤ ਕੀਤੀਆਂ ਚਿੱਤਰ SVG ਐਡੀਟਰਾਂ (Inkscape, ਆਦਿ) ਵਿੱਚ ਲਾਭਦਾਇਕ ਹੋ ਸਕਦੀਆਂ ਹਨ, ਪਰ ਕੁਝ CAM ਵਿੱਚੋਂ ਬਚਣਾ ਚਾਹੀਦਾ ਹੈ।",
        "ro_ro": "Imaginile exportate pot fi utile în editori SVG (Inkscape, etc.), dar trebuie evitate în anumite programe CAM.",
        "sk": "Exportované obrázky môžu byť užitočné v SVG editorech (Inkscape atď.), ale mali by sa vyhýbať v niektorých programech CAM.",
        "sl": "Izportirane slike so lahko koristne v urejevalnikih SVG (Inkscape itd.), vendar jih je treba izogniti v nekaterih CAM-programih.",
        "sq_al": "Imazhet e eksportuara mund të jenë të dobishme në editorë SVG (Inkscape, etj.), por duhet të përballen në disa CAM.",
        "sr": "Експортоване слике могу бити корисне у SVG уређачима (Inkscape, итд.), али треба их избећи у неким CAM програмима.",
        "ta": "ஏக்ஸ்போர்ட் செய்யப்பட்ட படங்கள் SVG எடிட்டர்களில் (Inkscape, போன்றவை) பயனுள்ளதாக இருக்கலாம், ஆனால் சில CAM இல் தவிர்க்கப்பட வேண்டும்.",
        "uk": "Експортовані зображення можуть бути корисними в SVG-редакторах (Inkscape та ін.), але їх слід уникати у деяких программах CAM.",
        "et": "Eksporditud pildid võivad olla kasulikud SVG-editorites (Inkscape jne.), kuid neid tuleb vältida mõnes CAM-is.",
        "lv": "Eksportētie attēli var būt noderīgi SVG redaktoros (Inkscape utt.), bet jāizvairo no dažiem CAM-programmām.",
    },
    "Many CAM&apos;s(MakerCAM, EleskCAM, LaserWeb) ignore dashed/doted line style, \nwhich can be useful in lasercut of plywood or for papercraft. ": {
        "zh_cn": "许多CAM软件（MakerCAM、EleskCAM、LaserWeb）忽略虚线/点线样式，这在胶合板激光切割或纸艺中可能有用。",
        "zh_tw": "許多CAM軟體（MakerCAM、EleskCAM、LaserWeb）忽略虛線/點線樣式，這在膠合板雷射切割或紙藝中可能有用。",
        "de": "Viele CAM-Programme (MakerCAM, EleskCAM, LaserWeb) ignorieren gestrichelte/punktierte Linienstile, die für Laserschnitte von Sperrholz oder für Papierhandwerk nützlich sein können.",
        "fr": "De nombreuses CAM (MakerCAM, EleskCAM, LaserWeb) ignorent le style de ligne en pointillés/tirets, qui peut être utile pour la découpe laser de contreplaqué ou pour le papiercraft.",
        "es": "Muchas CAM (MakerCAM, EleskCAM, LaserWeb) ignoran el estilo de línea discontinua/punteada, que puede ser útil en el corte láser de contrachapado o para manualidades de papel.",
        "ru": "Многие CAM (MakerCAM, EleskCAM, LaserWeb) игнорируют стиль пунктирных/точечных линий, который может быть полезен при лазерной резке фанеры или для бумажного искусства.",
        "ja": "多くのCAMソフトウェア（MakerCAM、EleskCAM、LaserWeb）は破線/点線スタイルを無視します。これは合板のレーザーカットやペーパークラフトに役立つ場合があります。",
        "ko": "많은 CAM 소프트웨어(MakerCAM, EleskCAM, LaserWeb)가 점선/파선 스타일을 무시합니다. 이는 합판 레이저 컷이나 종이 공예에 유용할 수 있습니다.",
        "it": "Molte CAM (MakerCAM, EleskCAM, LaserWeb) ignorano lo stile della linea tratteggiata/puntinata, che può essere utile nel taglio laser del legno compensato o per il papercraft.",
        "pt_pt": "Muitas CAM (MakerCAM, EleskCAM, LaserWeb) ignoram o estilo de linha tracejada/pontilhada, que pode ser útil no corte a laser de compensado ou para artesanato de papel.",
        "nl": "Veel CAM-programma's (MakerCAM, EleskCAM, LaserWeb) negeren gestippelde/gestreepte lijnstijlen, die nuttig kunnen zijn bij lasergravure van multiplex of voor papierkunst.",
        "pl": "Wiele programów CAM (MakerCAM, EleskCAM, LaserWeb) ignoruje styl linii przerywanej/kropkowanej, co może być przydatne przy cięciu laserowym sklejki lub do papierowych sztuk.",
        "hu": "Sok CAM-program (MakerCAM, EleskCAM, LaserWeb) figyelmen kívül hagyja a szaggatott/pontos vonalstílust, amely hasznos lehet fűtött fa lézer-vágásában vagy papírművészetben.",
        "cs": "Mnohé programy CAM (MakerCAM, EleskCAM, LaserWeb) ignorují styl přerušených/bodovaných čar, který může být užitečný při laserovém řezání desek nebo pro papírové umění.",
        "da": "Mange CAM-programmer (MakerCAM, EleskCAM, LaserWeb) ignorerer stiplede/prikkede linjestile, der kan være nyttige ved laserudskæring af fjerkræ eller til papirarbejde.",
        "sv": "Många CAM-program (MakerCAM, EleskCAM, LaserWeb) ignorerar streckade/punktliga linjestilar, som kan vara användbara vid laserskärning av limträ eller för pappershantverk.",
        "fi": "Monet CAM-ohjelmat (MakerCAM, EleskCAM, LaserWeb) jättävät huomiotta katkoviivujen/pistetoisten viivojen tyylin, joka voi olla hyödyllinen kerroslevyn laserleikkauksessa tai paperin käsityöissä.",
        "no": "Mange CAM-programmer (MakerCAM, EleskCAM, LaserWeb) ignorerer stiplede/prikkede linjestiler, som kan være nyttige ved laserskiving av fjærverket eller for papirarbeid.",
        "tr": "Birçok CAM (MakerCAM, EleskCAM, LaserWeb) kesikli/noktalı çizgi stilini görmezden gelir, bu da kontrplak lazer kesiminde veya kağıt sanatında faydalı olabilir.",
        "el": "Πολλές CAM (MakerCAM, EleskCAM, LaserWeb) αγνοούν το στυλ γραμμής με διακεκομμένες/διασπαρμένες γραμμές, το οποίο μπορεί να είναι χρήσιμο στην λέιζερ κοπή πλαϊνίου ή για χειροτεχνίες χαρτιού.",
        "he": "רבות מהמערכות CAM (MakerCAM, EleskCAM, LaserWeb) מתעלמות מעיצוב קו מנוקד/מנוקד, שעלול להיות שימושי בחיתוך לייזר של בלוי או לאומנות 종이.",
        "id_id": "Banyak CAM (MakerCAM, EleskCAM, LaserWeb) mengabaikan gaya garis putus-putus/titik-titik, yang dapat berguna dalam pemotongan laser kayu lapis atau untuk kerajinan kertas.",
        "th": "CAM หลายตัว (MakerCAM, EleskCAM, LaserWeb) ไม่สนใจสไตล์เส้นประ/จุด ซึ่งอาจเป็นประโยชน์ในการตัดเลเซอร์ไม้พื้นหรือสำหรับงานกระดาษ",
        "ar": "كثير من برامج CAM (MakerCAM، EleskCAM، LaserWeb) تجاهل نمط الخطوط المتقطعة/المقطعة، والذي يمكن أن يكون مفيدًا في قطع البلوك بالليزر أو للفن الورقي.",
        "ca": "Moltes CAM (MakerCAM, EleskCAM, LaserWeb) ignoren l'estil de línia discontinua/puntada, que pot ser útil en el tall làser de contraplacat o per a artesanat de paper.",
        "eu": "CAM programa asko (MakerCAM, EleskCAM, LaserWeb) ez dira kontuan hartzen lerro estilu hautatsu/puntuatutakoak, lasereko estaldura edo paper artesanatuan baliagarriak izan daitezkeenak.",
        "gl": "Moitas CAM (MakerCAM, EleskCAM, LaserWeb) ignoran o estilo de liña discontinuada/punteada, que pode ser útil no corte láser de contrachapado ou para artesanía de papel.",
        "hi": "कई CAM सॉफ्टवेयर (MakerCAM, EleskCAM, LaserWeb) डैश्ड/डॉटेड लाइन स्टाइल को अनदेखा करते हैं, जो प्लाईवुड के लेजर कट या पेपरक्राफ्ट में उपयोगी हो सकती है।",
        "ka": "ბევრი CAM პროგრამა (MakerCAM, EleskCAM, LaserWeb) უგულებელყოფს შეწყვეტილი/წერტილი ხაზის სტილს, რომელიც შეიძლება სასარგებლო იყოს ფენოვანი ხის ლაზერული გაჭრობაში ან ქაღალდის ხელოვნებაში.",
        "mk": "Многу CAM програми (MakerCAM, EleskCAM, LaserWeb) ги игнорираат стиловите на прекини/точки линии, што може да биде корисно при ласерно резање на ламиниран дърво или за хартиени ремесла.",
        "pa": "ਬਹੁਤ ਸਾਰੇ CAM ਸੌਫਟਵੇਅਰ (MakerCAM, EleskCAM, LaserWeb) ਡੈਸ਼ਡ/ਡੋਟੇਡ ਲਾਈਨ ਸਟਾਈਲ ਨੂੰ ਨਜ਼ਰਅੰਦਾਜ਼ ਕਰਦੇ ਹਨ, ਜੋ ਪਲਾਈਵੁੱਡ ਦੇ ਲੇਜ਼ਰ ਕੱਟ ਜਾਂ ਪੇਪਰਕ੍ਰਾਫਟ ਵਿੱਚ ਲਾਭਦਾਇਕ ਹੋ ਸਕਦੀ ਹੈ।",
        "ro_ro": "Multe programe CAM (MakerCAM, EleskCAM, LaserWeb) ignoră stilul liniei discontinuate/punctate, care poate fi util în tăierea cu laser a plăcilor sandwich sau pentru artizanat de hârtie.",
        "sk": "Mnohé programy CAM (MakerCAM, EleskCAM, LaserWeb) ignorujú štýl prerušených/bodovaných čiar, ktorý môže byť užitočný pri laserovom reze lamelovaných dosiek alebo pre papierové umenie.",
        "sl": "Mnoge CAM-programi (MakerCAM, EleskCAM, LaserWeb) ignorirajo slog prekinjenih/črkastih črt, ki je lahko koristen pri laserskem rezanju laminiranega lesa ali za papirne izdelke.",
        "sq_al": "Shumë CAM (MakerCAM, EleskCAM, LaserWeb) ignorojnë stilin e rreshtave të ndërprerë/punktë, që mund të jetë i dobishëm në prerje me laser të pllaksave ose për artesanat të letë.",
        "sr": "Многе CAM програме (MakerCAM, EleskCAM, LaserWeb) игноришу стил прекинутих/тачкастих линија, што може бити корисно при лазерском резању ламинираног дрвета или за хартијане ремесла.",
        "ta": "பல CAM மென்பொருள்கள் (MakerCAM, EleskCAM, LaserWeb) கிழிந்த/புள்ளி புள்ளி வரி பாணியை புறக்கணிக்கின்றன, இது பிளைய்வுட் லேசர் கட்டல் அல்லது காகிதக்கலை மேல் பயனுள்ளதாக இருக்கலாம்.",
        "uk": "Багато програм CAM (MakerCAM, EleskCAM, LaserWeb) ігнорують стиль штрихпунктирних/точкових ліній, що може бути корисним при лазерномурізі фанери або для паперової творчості.",
        "et": "Paljud CAM-programmid (MakerCAM, EleskCAM, LaserWeb) ignoreerivad katkendlikke/punktisi jooni stiile, mis võivad olla kasulikud lamineeritud puu laserlõigutamisel või papiriteostustes.",
        "lv": "Dažādas CAM-programmas (MakerCAM, EleskCAM, LaserWeb) ignorē atstāžu/punktu līniju stili, kas var būt noderīgi laminētā koka lāzerķermeņā vai papīra darbos.",
    },
    "Default width of elements can affect some CAM&apos;s/SVG Editors, \nbut ignored by other": {
        "zh_cn": "元素的默认宽度可能会影响某些CAM软件/SVG编辑器，但其他软件会忽略它。",
        "zh_tw": "元素的預設寬度可能會影響某些CAM軟體/SVG編輯器，但其他軟體會忽略它。",
        "de": "Die Standardbreite von Elementen kann einige CAM-Programme/SVG-Editoren beeinflussen, wird aber von anderen ignoriert.",
        "fr": "La largeur par défaut des éléments peut affecter certaines CAM/éditeurs SVG, mais est ignorée par d'autres.",
        "es": "El ancho predeterminado de los elementos puede afectar a algunas CAM/editores SVG, pero otros lo ignoran.",
        "ru": "Стандартная ширина элементов может влиять на некоторые программы CAM/SVG-редакторы, но другие игнорируют ее.",
        "ja": "要素のデフォルト幅は一部のCAMソフトウェア/SVGエディタに影響を与える場合がありますが、他のソフトウェアでは無視されます。",
        "ko": "요소의 기본 너비는 일부 CAM 소프트웨어/SVG 편집기에 영향을 줄 수 있지만, 다른 소프트웨어에서는 무시됩니다.",
        "it": "La larghezza predefinita degli elementi può influenzare alcune CAM/editor SVG, ma viene ignorata da altre.",
        "pt_pt": "A largura padrão dos elementos pode afetar algumas CAM/editores SVG, mas é ignorada por outros.",
        "nl": "De standaardbreedte van elementen kan sommige CAM-programma's/SVG-editors beïnvloeden, maar wordt door andere genegeerd.",
        "pl": "Domyślna szerokość elementów może wpływać na niektóre programy CAM/edytory SVG, ale jest ignorowana przez inne.",
        "hu": "Az elemek alapértelmezett szélessége befolyásolhatja egyes CAM-programokat/SVG-szerkesztőket, de mások figyelmen kívül hagyják.",
        "cs": "Výchozí šířka prvků může ovlivnit některé programy CAM/SVG editory, ale jinými je ignorována.",
        "da": "Standardbredden på elementer kan påvirke nogle CAM-programmer/SVG-redigerede, men ignoreres af andre.",
        "sv": "Standardbredden på element kan påverka vissa CAM-program/SVG-redigerare, men ignoreras av andra.",
        "fi": "Elementtien oletusleveys voi vaikuttaa joidenkin CAM-ohjelmien/SVG-editorien toimintaan, mutta toiset ohjelmat jättävät sen huomiotta.",
        "no": "Standardbredden til elementer kan påvirke noen CAM-programmer/SVG-redigerere, men ignoreres av andre.",
        "tr": "Öğelerin varsayılan genişliği bazı CAM/SVG Editörlerini etkileyebilir, ancak diğerleri tarafından görmezden gelinir.",
        "el": "Το προκαθορισμένο πλάτος των στοιχείων μπορεί να επηρεάσει ορισμένες CAM/επεξεργαστές SVG, αλλά αγνοείται από άλλους.",
        "he": "רוחב ברירת המחדל של אלמנטים עשוי להשפיע על חלק מהמערכות CAM/עורכים SVG, אך אחרות מתעלמות ממנו.",
        "id_id": "Lebar default elemen dapat mempengaruhi beberapa CAM/Penyunting SVG, tetapi diabaikan oleh yang lain.",
        "th": "ความกว้างเริ่มต้นขององค์ประกอบอาจส่งผลกระทบต่อ CAM/SVG Editor บางตัว แต่จะถูกตัวอื่น ๆ ปราศจากความสนใจ",
        "ar": "العرض الافتراضي للعناصر يمكن أن يؤثر على بعض برامج CAM/محرري SVG، ولكن يتم تجاهله من قبل آخرين.",
        "ca": "L'amplada per defecte dels elements pot afectar algunes CAM/editors SVG, però és ignorada per d'altres.",
        "eu": "Elementuen lehenetsitako zabalera batzuk CAM-programak/SVG-editoreak eragin ditzake, baina besteek kontuan ez hartzen.",
        "gl": "A anchura por defecto dos elementos pode afectar a algúns CAM/editores SVG, pero outros a ignoran.",
        "hi": "तत्वों की डिफ़ॉल्ट चौड़ाई कुछ CAM सॉफ्टवेयर/SVG एडिटरों को प्रभावित कर सकती है, लेकिन अन्यों द्वारा अनदेखा की जाती है।",
        "ka": "ელემენტების ნაგულისხმევი სიგანე შეიძლება გავლენას მოახდინოს ზოგიერთ CAM პროგრამას/SVG რედაქტორს, მაგრამ სხვები უგულებელყოფენ მას.",
        "mk": "Стандардна ширина на елементи може да влијае на некои CAM програми/SVG уредувачи, но други ги игнорираат.",
        "pa": "ਤੱਤਾਂ ਦੀ ਡਿਫਾਲਟ ਚੌੜਾਈ ਕੁਝ CAM ਸੌਫਟਵੇਅਰ/SVG ਐਡੀਟਰਾਂ ਨੂੰ ਪ੍ਰਭਾਵਿਤ ਕਰ ਸਕਦੀ ਹੈ, ਪਰ ਦੂਸਰਿਆਂ ਦੁਆਰਾ ਅਣਦेखਾ ਕੀਤੀ ਜਾਂਦੀ ਹੈ।",
        "ro_ro": "Lățimea implicită a elementelor poate afecta unele programe CAM/editori SVG, dar este ignorată de altele.",
        "sk": "Predvolená šírka prvkov môže ovplyvniť niektoré programy CAM/SVG editory, ale inými je ignorovaná.",
        "sl": "Privzeta širina elementov lahko vpliva na nekatere CAM-programe/ureditelje SVG, vendar jo drugi ignorirajo.",
        "sq_al": "Gjerësia e parazgjedhur e elementeve mund të ndikojë në disa CAM/editorë SVG, por është e ignoruar nga të tjerët.",
        "sr": "Стандардна ширина елемената може да утиче на неке CAM програме/SVG уређаче, али их други игноришу.",
        "ta": "உறுப்புகளின் இயல்புநிலை அகலம் சில CAM மென்பொருள்கள்/SVG எடிட்டர்களை பாதிக்கலாம், ஆனால் மற்றவர்களால் புறக்கணிக்கப்படுகிறது.",
        "uk": "За замовчуванням ширина елементів може впливати на деякі програми CAM/SVG-редактори, але інші ігнорують її.",
        "et": "Elementide vaikimisi laius võib mõjutada mõnda CAM-programmi/SVG-editorit, kuid teised ignoreerivad seda.",
        "lv": "Elementu noklusējuma platums var ietekmēt dažas CAM-programmas/SVG redaktorus, bet tos ignorē citi.",
    },
    "Length of line pattern related to zoom,": {
        "zh_cn": "线型长度与缩放相关，", "zh_tw": "線型長度與縮放相關，",
        "de": "Länge des Linienmusters hängt von der Zoomstufe ab,",
        "fr": "La longueur du motif de ligne dépend du zoom,",
        "es": "La longitud del patrón de línea está relacionada con el zoom,",
        "ru": "Длина линий зависит от масштаба,",
        "ja": "線パターンの長さはズームに関連しています,",
        "ko": "선 패턴 길이가 줌과 관련됩니다,",
        "it": "Lunghezza del pattern di linea correlata allo zoom,",
        "pt_pt": "Comprimento do padrão de linha relacionado ao zoom,",
        "nl": "Lengte van het lijnpatroon is gerelateerd aan de zoom,",
        "pl": "Długość wzoru linii zależna od zoomu,",
        "hu": "A vonalpátternhossz a nagyítás függvénye,",
        "cs": "Délka vzoru čáry je spojena s zoomem,",
        "da": "Længde på linjemønster relateret til zoom,",
        "sv": "Linjemönstrets längd relaterad till zoom,",
        "fi": "Viivakuvion pituus liittyy zoomiin,",
        "no": "Lengde på linjemønster knyttet til zoom,",
        "tr": "Çizgi deseninin uzunluğu zoom ile ilişkilidir,",
        "el": "Το μήκος του patroon γραμμής σχετίζεται με το zoom,",
        "he": "אורך דפוס הקו קשור לזום,",
        "id_id": "Panjang pola garis terkait zoom,",
        "th": "ความยาวของรูปแบบเส้นเกี่ยวข้องกับการซูม,",
        "ar": "طول نمط الخط مرتبط بالتصغير،",
        "ca": "La longitud del patró de línia està relacionada amb el zoom,",
        "eu": "Lerroaren patroia luzera zoomarekin lotuta dago,",
        "gl": "A lonxitude do patrón de liña está relacionada co zoom,",
        "hi": "लाइन पैटर्न की लंबाई ज़ूम से संबंधित है,",
        "ka": "ხაზის ნიმუშის სიგრძე ზუმთან დაკავშირებულია,",
        "mk": "Должина на линискиот облик поврзана со зумирање,",
        "pa": "ਲਾਈਨ ਪੈਟਰਨ ਦੀ ਲੰਬਾਈ ਜ਼ੂਮ ਨਾਲ ਸਬੰਧਤ ਹੈ,",
        "ro_ro": "Lungimea modelului de linie este legată de zoom,",
        "sk": "Dĺžka vzoru čiary súvisí so zoomom,",
        "sl": "Dolžina vzorca črte je povezana z zumom,",
        "sq_al": "Gjata e模式it të rreshtit është e lidhur me zoom,",
        "sr": "Дужина линије повезана са зумиранјем,",
        "ta": "கோடு முறையின் நீளம் சூமுடன் தொடர்புடையது,",
        "uk": "Довжина лінійного патерну пов'язана з зумом,",
        "et": "Joone musteripikkus on seotud zumiga,",
        "lv": "Līnijas modeļa garums ir saistīts ar zumu,",
    },
    "MakerCAM as of March 2015 cannot display ellipses and ellipse arcs correctly, \nwhen they are created using the &lt;ellipse&gt; tag  with a rotation in \nthe &lt;transform&gt; attribute or as &lt;path&gt; using elliptic arc segments.": {
        "zh_cn": "截至2015年3月，MakerCAM无法正确显示椭圆和椭圆弧，当它们使用带有旋转的&lt;ellipse&gt;标签在&lt;transform&gt;属性中创建或作为&lt;path&gt;使用椭圆弧段创建时。",
        "zh_tw": "截至2015年3月，MakerCAM無法正確顯示橢圓和橢圓弧，當它們使用帶有旋轉的&lt;ellipse&gt;標籤在&lt;transform&gt;屬性中創建或作為&lt;path&gt;使用橢圓弧段創建時。",
        "de": "MakerCAM ab März 2015 kann Ellipsen und Ellipsenbögen nicht korrekt anzeigen, wenn sie unter Verwendung des &lt;ellipse&gt;-Tags mit Rotation im &lt;transform&gt;-Attribut oder als &lt;path&gt; unter Verwendung von Ellipsenbogensegmenten erstellt werden.",
        "fr": "MakerCAM depuis mars 2015 ne peut pas afficher correctement les ellipses et les arcs d'ellipse, lorsqu'ils sont créés à l'aide de la balise &lt;ellipse&gt; avec une rotation dans l'attribut &lt;transform&gt; ou comme &lt;path&gt; à l'aide de segments d'arc elliptique.",
        "es": "MakerCAM a partir de marzo de 2015 no puede mostrar correctamente las elipses y los arcos elípticos, cuando se crean usando la etiqueta &lt;ellipse&gt; con una rotación en el atributo &lt;transform&gt; o como &lt;path&gt; usando segmentos de arco elíptico.",
        "ru": "MakerCAM с марта 2015 года не может корректно отображать эллипсы и дуги эллипсов, когда они создаются с использованием тега &lt;ellipse&gt; с вращением в атрибуте &lt;transform&gt; или как &lt;path&gt; с использованием эллиптических дуг.",
        "ja": "2015年3月現在、MakerCAMは楕円および楕円弧を正しく表示できません。&lt;ellipse&gt;タグを使用して&lt;transform&gt;属性に回転を指定して作成された場合、または&lt;path&gt;として楕円弧セグメントを使用して作成された場合です。",
        "ko": "2015년 3월 현재 MakerCAM은 타원 및 타원 호를 올바르게 표시할 수 없습니다. &lt;ellipse&gt; 태그를 사용하여 &lt;transform&gt; 속성에 회전이 있는 경우 또는 &lt;path&gt;로 타원 호 세그먼트를 사용하는 경우입니다.",
        "it": "MakerCAM a marzo 2015 non può visualizzare correttamente le ellissi e gli archi ellittici, quando vengono creati utilizzando il tag &lt;ellipse&gt; con una rotazione nell'attributo &lt;transform&gt; o come &lt;path&gt; utilizzando segmenti di arco ellittico.",
        "pt_pt": "MakerCAM a partir de março de 2015 não consegue exibir elipses e arcos elípticos corretamente, quando são criados usando a etiqueta &lt;ellipse&gt; com uma rotação no atributo &lt;transform&gt; ou como &lt;path&gt; usando segmentos de arco elíptico.",
        "nl": "MakerCAM vanaf maart 2015 kan ellipsen en ellipsbogen niet correct weergeven, wanneer ze worden gemaakt met behulp van de &lt;ellipse&gt;-tag met rotatie in het &lt;transform&gt;-attribuut of als &lt;path&gt; met ellipsboogsegmenten.",
        "pl": "MakerCAM od marca 2015 roku nie może poprawnie wyświetlać elips i łuków eliptycznych, gdy są one tworzone za pomocą tagu &lt;ellipse&gt; z rotacją w atrybucie &lt;transform&gt; lub jako &lt;path&gt; z użyciem łuków eliptycznych.",
        "hu": "A MakerCAM a 2015. március óta nem tudja helyesen megjeleníteni az ellipsziséket és az ellipszis íveket, amikor azokat az &lt;ellipse&gt; címke segítségével, forgatásával a &lt;transform&gt; attribútumban vagy az &lt;path&gt;ként, ellipszis ívszegmensekkel hozza létre.",
        "cs": "MakerCAM od března 2015 nemůže správně zobrazovat elipsy a eliptické oblouky, když jsou vytvořeny pomocí tagu &lt;ellipse&gt; s rotací v atributu &lt;transform&gt; nebo jako &lt;path&gt; s využitím eliptických obloukových segmentů.",
        "da": "MakerCAM fra marts 2015 kan ikke vise ellipsen og ellipsebuene korrekt, når de oprettes ved hjælp af &lt;ellipse&gt;-tagget med rotation i &lt;transform&gt;-attributten eller som &lt;path&gt; ved hjælp af ellipsebuesegmenter.",
        "sv": "MakerCAM från mars 2015 kan inte visa ellipser och ellipsbågar korrekt, när de skapas med hjälp av &lt;ellipse&gt;-taggen med rotation i &lt;transform&gt;-attributet eller som &lt;path&gt; med ellipsbågssegment.",
        "fi": "MakerCAM marraskuusta 2015 eteenpäin ei voi näyttää ellipsejä ja ellipsin kaaria oikein, kun ne luodaan käyttämällä &lt;ellipse&gt;-tagia pyöräytyksellä &lt;transform&gt;-attribuutissa tai &lt;path&gt;-tagina käyttäen ellipsin kaarisegmenttejä.",
        "no": "MakerCAM fra mars 2015 kan ikke vise ellipsene og ellipsebuene korrekt, når de opprettes ved hjelp av &lt;ellipse&gt;-taggen med rotasjon i &lt;transform&gt;-attributtet eller som &lt;path&gt; ved hjelp av ellipsebuesegmenter.",
        "tr": "MakerCAM Mart 2015'ten itibaren elipsleri ve elips arklarını doğru olarak görüntüleyemiyor, bunlar &lt;ellipse&gt; etiketi kullanılarak &lt;transform&gt; özniteliğinde bir döndürme ile oluşturulduğunda veya &lt;path&gt; olarak elips arkı segmentleri kullanılarak oluşturulduğunda.",
        "el": "Το MakerCAM από τον Μάρτιο του 2015 δεν μπορεί να εμφανίσει σωστά οι έλλειψεις και οι τόξοι έλλειψης, όταν δημιουργούνται χρησιμοποιώντας την ετικέτα &lt;ellipse&gt; με περιστροφή στο χαρακτηριστικό &lt;transform&gt; ή ως &lt;path&gt; χρησιμοποιώντας τμήματα έλλειψης τόξου.",
        "he": "MakerCAM מ� مارس 2015 אינו מסוגל להציג אליפסים וקשתות אליפסיס בצורה נכונה, כאשר הן נוצרות באמצעות התג &lt;ellipse&gt; עם סיבוב באלמנט &lt;transform&gt; או כ-&lt;path&gt; באמצעות קטעים של קשת אליפסיס.",
        "id_id": "MakerCAM sejak Maret 2015 tidak dapat menampilkan elips dan busur elips dengan benar, ketika mereka dibuat menggunakan tag &lt;ellipse&gt; dengan rotasi dalam atribut &lt;transform&gt; atau sebagai &lt;path&gt; menggunakan segmen busur elips.",
        "th": "MakerCAM ตั้งแต่ มีนาคม 2015 ไม่สามารถแสดงวงรีและอาร์ควงรีได้อย่างถูกต้อง เมื่อสร้างโดยใช้แท็ก &lt;ellipse&gt; พร้อมการหมุนในแอตทริบิวต์ &lt;transform&gt; หรือเป็น &lt;path&gt; โดยใช้เซ็กเมนต์อาร์ควงรี",
        "ar": "MakerCAM منذ مارس 2015 لا يمكنه عرض الأقطاب الناقص والأقواس الناقصة بشكل صحيح، عندما يتم إنشاؤها باستخدام العلامة &lt;ellipse&gt; مع دوران في السمة &lt;transform&gt; أو كـ &lt;path&gt; باستخدام مقاطع القوس الإهليجي.",
        "ca": "MakerCAM des de març de 2015 no pot mostrar correctament les el·lipses i els arcs el·líptics, quan es creen utilitzant l'etiqueta &lt;ellipse&gt; amb rotació en l'atribut &lt;transform&gt; o com &lt;path&gt; utilitzant segments d'arc el·líptic.",
        "eu": "MakerCAM martxoaren 2015az geroztik ezin du elipsak eta elips-arkuak zuzenki erakutsi, &lt;ellipse&gt; etiketa erabiliz sortzen direnean &lt;transform&gt; atributuan birakuntza batekin edo &lt;path&gt; gisa elips-arku segmentuak erabiliz.",
        "gl": "MakerCAM desde marzo de 2015 non pode mostrar correctamente as elipses e os arcos elípticos, cando se crean usando a etiqueta &lt;ellipse&gt; con rotación no atributo &lt;transform&gt; ou como &lt;path&gt; usando segmentos de arco elíptico.",
        "hi": "March 2015 तक MakerCAM दीर्घवृत्तों और दीर्घवृत्त चापों को सही ढंग से प्रदर्शित नहीं कर सकता, जब वे &lt;ellipse&gt; टैग का उपयोग करके &lt;transform&gt; गुण में एक रोटेशन के साथ बनाए जाते हैं या &lt;path&gt; के रूप में दीर्घवृत्त चाप खंडों का उपयोग करते हैं।",
        "ka": "MakerCAM 2015 წლის მარტიდან ვერ აჩვენებს ელიფსებს და ელიფსის რკალებს სწორად, როდესაც ისინი &lt;ellipse&gt; ტეგის გამოყენებით &lt;transform&gt; ატრიბუტში როტაციით ან &lt;path&gt; olarak ellipse ark segmentleri kullanılarak oluşturulduğunda.",
        "mk": "MakerCAM од март 2015 година не може да ги прикаже правилно елрипсите и елрипските лукови, кога тие се креираат со користење на тагот &lt;ellipse&gt; со ротација во атрибутот &lt;transform&gt; или како &lt;path&gt; со користење на елрипски лукови сегменти.",
        "pa": "ਮਾਰਚ 2015 ਤੱਕ MakerCAM ਦीर्घਵृत्तਾਂ ਅਤੇ ਦीर्घਵृतਤ ਚਾਪਾਂ ਨੂੰ ਸਹੀ ਢੰਗ ਨਾਲ ਪ੍ਰਦਰਸ਼ਿਤ ਨਹੀਂ ਕਰ ਸਕਦਾ, ਜਦੋਂ ਉਹ &lt;ellipse&gt; ਟੈਗ ਦੀ ਵਰਤੋਂ ਕਰਕੇ &lt;transform&gt; ਅਟਰਬਿਊਟ ਵਿੱਚ ਰੋਟੇਸ਼ਨ ਦੇ ਨਾਲ ਬਣਾਏ ਜਾਂਦੇ ਹਨ ਜਾਂ &lt;path&gt; ਦੇ ਰੂਪ ਵਿੱਚ ਦीर्घਵृतਤ ਚਾਪ ਸੈਗਮੈਂਟਸ ਦੀ ਵਰਤੋਂ ਕਰਦੇ ਹਨ।",
        "ro_ro": "MakerCAM din martie 2015 nu poate afișa corect elipsele și arcele eliptice, atunci când acestea sunt create folosind tag-ul &lt;ellipse&gt; cu o rotație în atributul &lt;transform&gt; sau ca &lt;path&gt; folosind segmente de arc eliptic.",
        "sk": "MakerCAM od marca 2015 nemôže správne zobrazovať elipsy a eliptické oblouky, keď sú vytvárané pomocou tagu &lt;ellipse&gt; s rotáciou v atribúte &lt;transform&gt; alebo ako &lt;path&gt; s použitím eliptických obloukových segmentov.",
        "sl": "MakerCAM od marca 2015 ne more pravilno prikazati elips in eliptičnih lukov, kadar jih ustvarimo z uporabo značke &lt;ellipse&gt; z rotacijo v atributu &lt;transform&gt; ali kot &lt;path&gt; z uporabo eliptičnih lukovnih segmentov.",
        "sq_al": "MakerCAM nga marsi 2015 nuk mund të shfaqë elipsat dhe arkët eliptike korrekt, kur ato krijohen duke përdorur etiketën &lt;ellipse&gt; me rrotullim në atributin &lt;transform&gt; ose si &lt;path&gt; duke përdorur segmente të arkës eliptike.",
        "sr": "MakerCAM од марта 2015. године не може да прикаже правилно елипсе и елиптичне лукове, када се креирају користећи таг &lt;ellipse&gt; са ротацијом у атрибуту &lt;transform&gt; или као &lt;path&gt; користећи елиптичне лук сегменте.",
        "ta": "மார்ச் 2015 முதல் MakerCAM ஆன ellipகளையும் ellipக் வளைவுகளையும் சரியாகக் காட்ட முடியாது, அவை &lt;ellipse&gt; டேக்கைப் பயன்படுத்தி &lt;transform&gt; பண்பு விதியில் சுழற்சியுடன் உருவாக்கப்படும் போது அல்லது &lt;path&gt; olarak ellip arc segmentleri kullanılarak oluşturulduğunda.",
        "uk": "MakerCAM з березня 2015 року не може коректно відображати еліпси та еліптичні дуги, коли вони створюються за допомогою тегу &lt;ellipse&gt; з обертанням у атрибуті &lt;transform&gt; або як &lt;path&gt; з використанням еліптичних дугових сегментів.",
        "et": "MakerCAM alates märts 2015 ei saa ellipseid ja ellipsi kaareid korrektselt kuvada, kui neid loetakse &lt;ellipse&gt;-sildi abil pööramine &lt;transform&gt;-atribuutis või &lt;path&gt;-sildi abil ellipsi kaarsegmentidega.",
        "lv": "MakerCAM no marta 2015 nevar korekti parādīt elipses un eliptiskās loksnes, kad tās tiek izveidotas, izmantojot &lt;ellipse&gt; tagu ar rotāciju &lt;transform&gt; atribūtā vai kā &lt;path&gt;, izmantojot eliptiskās loksnes segmentus.",
    },
    "Length of line pattern related to zoom, \nso default step value required for baking": {
        "zh_cn": "线型长度与缩放相关，因此需要默认步长值进行烘焙。",
        "zh_tw": "線型長度與縮放相關，因此需要預設步長值進行烘焙。",
        "de": "Länge des Linienmusters hängt von der Zoomstufe ab, daher ist ein Standard-Schrittwert für das Backen erforderlich.",
        "fr": "La longueur du motif de ligne dépend du zoom, donc une valeur de pas par défaut est nécessaire pour la cuisson.",
        "es": "La longitud del patrón de línea está relacionada con el zoom, por lo que se requiere un valor de paso predeterminado para la cocción.",
        "ru": "Длина линий зависит от масштаба, поэтому требуется значение шага по умолчанию для выпечки.",
        "ja": "線パターンの長さはズームに関連しているため、ベイキングにはデフォルトのステップ値が必要です。",
        "ko": "선 패턴 길이가 줌과 관련되어 있으므로 베이킹에 기본 스텝 값이 필요합니다.",
        "it": "Lunghezza del pattern di linea correlata allo zoom, quindi è richiesta una valore di passo predefinito per la cottura.",
        "pt_pt": "Comprimento do padrão de linha relacionado ao zoom, portanto, é necessário um valor de passo padrão para assar.",
        "nl": "Lengte van het lijnpatroon is gerelateerd aan de zoom, daarom is een standaard stapwaarde nodig voor het bakken.",
        "pl": "Długość wzoru linii zależna od zoomu, dlatego wymagana jest domyślna wartość kroku do pieczenia.",
        "hu": "A vonalpátternhossz a nagyítás függvénye, ezért alapértelmezett lépésérték szükséges a sütéshez.",
        "cs": "Délka vzoru čáry je spojena s zoomem, proto je pro pečení potřeba výchozí hodnota kroku.",
        "da": "Længde på linjemønster relateret til zoom, derfor kræves en standardtrinværdi til bagning.",
        "sv": "Linjemönstrets längd relaterad till zoom, därför krävs ett standardstegsvärde för bakning.",
        "fi": "Viivakuvion pituus liittyy zoomiin, joten perustaso on tarpeellinen paistamiseen.",
        "no": "Lengde på linjemønster knyttet til zoom, derfor kreves en standardtrinnverdi for baking.",
        "tr": "Çizgi deseninin uzunluğu zoom ile ilişkilidir, bu nedenle pişirme için varsayılan adım değeri gereklidir.",
        "el": "Το μήκος του patroon γραμμής σχετίζεται με το zoom, επομένως απαιτείται μια προεπιλεγμένη τιμή βήματος για το ψήσιμο.",
        "he": "אורך דפוס הקו קשור לזום, ולכן יש צורך בערך צעד ברירת מחדל לאפייה.",
        "id_id": "Panjang pola garis terkait zoom, oleh karena itu diperlukan nilai langkah default untuk memanggang.",
        "th": "ความยาวของรูปแบบเส้นเกี่ยวข้องกับการซูม ดังนั้นจึงต้องมีค่า step เริ่มต้นสำหรับการอบ",
        "ar": "طول نمط الخط مرتبط بالتصغير، لذلك يلزم قيمة الخطوة الافتراضية للخبز.",
        "ca": "La longitud del patró de línia està relacionada amb el zoom, per tant, és necessària una valor de pas per defecte per a la cuina.",
        "eu": "Lerroaren patroia luzera zoomarekin lotuta dago, beraz, bakegaitzeko pausu balio lehenetsia behar da.",
        "gl": "A lonxitude do patrón de liña está relacionada co zoom, polo que é necesaria un valor de paso por defecto para a cociñón.",
        "hi": "लाइन पैटर्न की लंबाई ज़ूम से संबंधित है, इसलिए बेकिंग के लिए डिफ़ॉल्ट स्टेप मान आवश्यक है।",
        "ka": "ხაზის ნიმუშის სიგრძე ზუმთან დაკავშირებულია, ამიტომ საჭმლისთვის საჭიროა ნაგულისხმევი ნაბიჯის მნიშვნელობა.",
        "mk": "Должина на линискиот облик поврзана со зумирање, затоа е потребна стандардна вредност на чекор за печење.",
        "pa": "ਲਾਈਨ ਪੈਟਰਨ ਦੀ ਲੰਬਾਈ ਜ਼ੂਮ ਨਾਲ ਸਬੰਧਤ ਹੈ, ਇਸ ਲਈ ਬੇਕਿੰਗ ਲਈ ਡਿਫਾਲਟ ਸਟੈਪ ਮੁੱਲ ਲੋੜੀਂਦਾ ਹੈ।",
        "ro_ro": "Lungimea modelului de linie este legată de zoom, prin urmare, este necesară o valoare de pas implicită pentru coacere.",
        "sk": "Dĺžka vzoru čiary súvisí so zoomom, preto je potrebná predvolená hodnota kroku pre pečenie.",
        "sl": "Dolžina vzorca črte je povezana z zumom, zato je potrebna privzeta vrednost koraka za pečenje.",
        "sq_al": "Gjata e模式it të rreshtit është e lidhur me zoom, prandaj është e nevojshme një vlerë hapëse parazgjedhur për pjekjen.",
        "sr": "Дужина линије повезана са зумиранјем, затоа је потребна стандардна вредност корака за пекарство.",
        "ta": "கோடு முறையின் நீளம் சூமுடன் தொடர்புடையது, எனவே பேக்கிங்கிற்கு இயல்புநிலை படி மதிப்பு தேவையாகும்.",
        "uk": "Довжина лінійного патерну пов'язана з зумом, тому для випічки необхідне значення кроку за замовчуванням.",
        "et": "Joone musteripikkus on seotud zumiga, seepärast on vajalik vaikimisi sammuväärtus küpsetamiseks.",
        "lv": "Līnijas modeļa garums ir saistīts ar zumu, tādēļ ir nepieciešams noklusējuma soļa vērtība cepšanai.",
    },
    "&amp;OK": {
        "zh_cn": "&OK", "zh_tw": "&OK", "de": "&OK", "fr": "&OK",
        "es": "&OK", "ru": "&OK", "ja": "&OK", "ko": "&OK",
        "it": "&OK", "pt_pt": "&OK", "nl": "&OK", "pl": "&OK",
        "hu": "&OK", "cs": "&OK", "da": "&OK", "sv": "&OK",
        "fi": "&OK", "no": "&OK", "tr": "&OK", "el": "&OK",
        "he": "&OK", "id_id": "&OK", "th": "&OK", "ar": "&OK",
        "ca": "&OK", "eu": "&OK", "gl": "&OK", "hi": "&OK",
        "ka": "&OK", "mk": "&OK", "pa": "&OK", "ro_ro": "&OK",
        "sk": "&OK", "sl": "&OK", "sq_al": "&OK", "sr": "&OK",
        "ta": "&OK", "uk": "&OK", "et": "&OK", "lv": "&OK",
    },
    "Attempt to create layer with duplicating name. Duplicated layer name is \n[%1].\nPlease specify a different name.": {
        "zh_cn": "尝试创建具有重复名称的图层。重复的图层名称是\n[%1]。\n请指定一个不同的名称。",
        "zh_tw": "嘗試創建具有重複名稱的圖層。重複的圖層名稱是\n[%1]。\n請指定一個不同的名稱。",
        "de": "Versuch, eine Ebene mit doppeltem Namen zu erstellen. Der doppelte Ebenenname lautet\n[%1].\nBitte geben Sie einen anderen Namen an.",
        "fr": "Tentative de création d'un calque avec un nom en double. Le nom du calque en double est\n[%1].\nVeuillez spécifier un nom différent.",
        "es": "Intento de crear una capa con nombre duplicado. El nombre de capa duplicado es\n[%1].\nEspecifique un nombre diferente.",
        "ru": "Попытка создать слой с дублирующим именем. Дублированное имя слоя:\n[%1].\nПожалуйста, укажите другое имя.",
        "ja": "重複する名前のレイヤーを作成しようとしています。重複したレイヤー名は\n[%1]です。\n異なる名前を指定してください。",
        "ko": "중복된 이름의 레이어를 만들려고 시도했습니다. 중복된 레이어 이름은\n[%1]입니다.\n다른 이름을 지정하십시오.",
        "it": "Tentativo di creare un layer con nome duplicato. Il nome del layer duplicato è\n[%1].\nSpecificare un nome diverso.",
        "pt_pt": "Tentativa de criar uma camada com nome duplicado. O nome da camada duplicada é\n[%1].\nEspecifique um nome diferente.",
        "nl": "Poging tot het creëren van een laag met een dubbele naam. De dubbele laagnaam is\n[%1].\nGeef een andere naam op.",
        "pl": "Próba utworzenia warstwy zduplikowaną nazwą. Nazwa zduplikowanej warstwy to\n[%1].\nPodaj inna nazwę.",
        "hu": "Kísérlet egy réteg létrehozására duplikált névvel. A duplikált réteg neve:\n[%1].\nAdjon meg egy másik nevet.",
        "cs": "Pokus vytvoření vrstvy s duplicitním názvem. Duplicitní název vrstvy je\n[%1].\nZadejte prosím jiný název.",
        "da": "Forsøg på at oprette et lag med et duplikeret navn. Det duplikerede lagnavn er\n[%1].\nAngiv venligst et andet navn.",
        "sv": "Försök att skapa ett lager med ett duplicerat namn. Det duplicerade lagernamnet är\n[%1].\nAnge ett annat namn.",
        "fi": "Yritetään luoda kerros kaksoisnimeä. Kaksoisniminen kerrosnimi on\n[%1].\nAnna toinen nimi.",
        "no": "Forsøk på å opprette et lag med et duplisert navn. Det dupliserte lagnavnet er\n[%1].\nAngi venligst et annet navn.",
        "tr": "Tekrarlanmış isimli bir katman oluşturma girişimi. Tekrarlanmış katman ismi\n[%1]'dir.\nLütfen farklı bir isim belirtin.",
        "el": "Προσπάθεια δημιουργίας επιπέδου με διπλό όνομα. Το διπλό όνομα επιπέδου είναι\n[%1].\nΠαρακαλώ καθορίστε διαφορετικό όνομα.",
        "he": "ניסיון ליצור שכבה עם שם משוכפל. שם השכבה המשוכפל הוא\n[%1].\nאנא ספק שם אחר.",
        "id_id": "Percobaan membuat lapisan dengan nama yang duplikat. Nama lapisan yang duplikat adalah\n[%1].\nSilakan tentukan nama yang berbeda.",
        "th": "พยายามสร้างชั้นด้วยชื่อที่ซ้ำกัน ชื่อชั้นที่ซ้ำกันคือ\n[%1].\nโปรดระบุชื่ออื่น",
        "ar": "محاولة إنشاء طبقة باسم مكرر. اسم الطبقة المكرر هو\n[%1].\nيرجى تحديد اسم مختلف.",
        "ca": "Intent de crear una capa amb nom duplicat. El nom de la capa duplicada és\n[%1].\nEspecifiqueu un nom diferent.",
        "eu": "Izen bikoiztutako geruza bat sortu nahi da. Bikoiztutako geruza izena:\n[%1].\nMesedez eman izen bat desberdin.",
        "gl": "Intento de crear unha capa con nome duplicado. O nome da capa duplicado é\n[%1].\nEspecifique un nome diferente.",
        "hi": "डुप्लिकेट नाम वाली परत बनाने का प्रयास। डुप्लिकेट परत का नाम\n[%1] है।\nकृपया एक अलग नाम निर्दिष्ट करें।",
        "ka": "დუბლიკატური სახელით ფენის შექმნის შესდგომ. დუბლიკატური ფენის სახელი:\n[%1].\nგთხოვთ დაითვალოთ სხვა სახელი.",
        "mk": "Опыток за креирање на слој со дуплициранo име. Дуплицираното име на слојот е\n[%1].\nВе молиме да ја наведете друга име.",
        "pa": "ਡੁਪਲਿਕੇਟ ਨਾਮ ਵਾਲੀ ਲੇਅਰ ਬਣਾਉਣ ਦੀ ਕੋਸ਼ਿਸ਼। ਡੁਪਲਿਕੇਟ ਲੇਅਰ ਦਾ ਨਾਮ\n[%1] ਹੈ।\nਕਿਰਪਾ ਕਰਕੇ ਇੱਕ ਵੱਖਰਾ ਨਾਮ ਨਿਰਧਾਰਤ ਕਰੋ।",
        "ro_ro": "Încercare de creare a unui strat cu nume duplicat. Numele stratului duplicat este\n[%1].\nSpecificați un nume diferit.",
        "sk": "Pokus vytvorenia vrstvy s duplicitným názvom. Duplicitný názov vrstvy je\n[%1].\nZadajte prosím iný názov.",
        "sl": "Poskus ustvarjanja plasti z podvojenim imenom. Podvojeno ime plasti je\n[%1].\nNavedite drug ime.",
        "sq_al": "Përpjekje për të krijuar një shtresë me emër i përsëritur. Emri i shtresës së përsëritur është\n[%1].\nJu lutemi specifikoni një emër të ndryshëm.",
        "sr": "Покушај креирања слоја са дуплицираног имена. Дуплициранио име слоја је\n[%1].\nМолим да наведете друго име.",
        "ta": "நகலெடுக்கப்பட்ட பெயரைக் கொண்ட ஒரு அடுக்கை உருவாக்க முயற்சி. நகலெடுக்கப்பட்ட அடுக்கைப் பெயர்\n[%1] ஆகும்.\nதவிர்வுப் பெயரைக் கொடுக்கவும்.",
        "uk": "Спроба створити шар з дублікованим ім'ям. Дубліковане ім'я шару:\n[%1].\nБудь ласка, вкажіть інше ім'я.",
        "et": "Püüdlus luua kiht dubleeritud nimega. Dubleeritud kihtinimi on\n[%1].\nPalun määrake teine nimi.",
        "lv": "Mēģinājums izveidot slāni ar dublēto nosaukumu. Dublētais slāņa nosaukums ir\n[%1].\nLūdzu norādiet citu nosaukumu.",
    },
    "Such child layer already exist for \n[%1].\nPlease specify a different name.": {
        "zh_cn": "此子图层已存在于\n[%1]中。\n请指定一个不同的名称。",
        "zh_tw": "此子圖層已存在於\n[%1]中。\n請指定一個不同的名稱。",
        "de": "Ein solcher untergeordneter Layer existiert bereits für\n[%1].\nBitte geben Sie einen anderen Namen an.",
        "fr": "Un tel sous-calque existe déjà pour\n[%1].\nVeuillez spécifier un nom différent.",
        "es": "Ya existe una subcapa como esta para\n[%1].\nEspecifique un nombre diferente.",
        "ru": "Такой дочерний слой уже существует для\n[%1].\nПожалуйста, укажите другое имя.",
        "ja": "このような子レイヤーはすでに存在します\n[%1]の場合。\n異なる名前を指定してください。",
        "ko": "이러한 하위 레이어는 이미 존재합니다\n[%1]에 대해.\n다른 이름을 지정하십시오.",
        "it": "Un tale sottolayer esiste già per\n[%1].\nSpecificare un nome diverso.",
        "pt_pt": "Já existe uma subcamada como esta para\n[%1].\nEspecifique um nome diferente.",
        "nl": "Een dergelijke sublaag bestaat al voor\n[%1].\nGeef een andere naam op.",
        "pl": "Taki podlayer już istnieje dla\n[%1].\nPodaj inna nazwę.",
        "hu": "Már létezik ilyen gyermekréteg a következőhöz:\n[%1].\nAdjon meg egy másik nevet.",
        "cs": "Taková podvrstva již existuje pro\n[%1].\nZadejte prosím jiný název.",
        "da": "En sådan underlag findes allerede for\n[%1].\nAngiv venligst et andet navn.",
        "sv": "En sådan underlager finns redan för\n[%1].\nAnge ett annat namn.",
        "fi": "Sellainen alakerros on jo olemassa\n[%1].\nAnna toinen nimi.",
        "no": "En slik underlag eksisterer allerede for\n[%1].\nAngi venligst et annet navn.",
        "tr": "Böyle bir alt katman zaten var\n[%1].\nLütfen farklı bir isim belirtin.",
        "el": "Ένας τέτοιος υπο-επίπεδος υπάρχει ήδη για\n[%1].\nΠαρακαλώ καθορίστε διαφορετικό όνομα.",
        "he": "� שכבה ילדה כזו כבר קיימת עבור\n[%1].\nאנא ספק שם אחר.",
        "id_id": "Lapisan anak seperti ini sudah ada untuk\n[%1].\nSilakan tentukan nama yang berbeda.",
        "th": "ชั้นย่อยดังกล่าวมีอยู่แล้วสำหรับ\n[%1].\nโปรดระบุชื่ออื่น",
        "ar": "هذه الطبقة الفرعية موجودة بالفعل ل\n[%1].\nيرجى تحديد اسم مختلف.",
        "ca": "Ja existeix una subcapa com aquesta per a\n[%1].\nEspecifiqueu un nom diferent.",
        "eu": "Geroago geruza bat dagoeneko dago:\n[%1].\nMesedez eman izen bat desberdin.",
        "gl": "Xa existe unha subcapa como esta para\n[%1].\nEspecifique un nome diferente.",
        "hi": "इस तरह की चाइल्ड लेयर पहले से मौजूद है\n[%1] के लिए।\nकृपया एक अलग नाम निर्दिष्ट करें।",
        "ka": "ასეთი ქ gyermek ფენა უკვე არსებობს\n[%1].-ზე.\nგთხოვთ დაითვალოთ სხვა სახელი.",
        "mk": "Таква детска слој веќе постои за\n[%1].\nВе молиме да ја наведете друга име.",
        "pa": "ਇਸ ਤਰ੍ਹਾਂ ਦੀ ਚਾਈਲਡ ਲੇਅਰ ਪਹਿਲਾਂ ਹੀ ਮੌਜੂਦ ਹੈ\n[%1] ਲਈ.\nਕਿਰਪਾ ਕਰਕੇ ਇੱਕ ਵੱਖਰਾ ਨਾਮ ਨਿਰਧਾਰਤ ਕਰੋ।",
        "ro_ro": "Un astfel de sub-strat există deja pentru\n[%1].\nSpecificați un nume diferit.",
        "sk": "Takáto podvrstva už existuje pre\n[%1].\nZadajte prosím iný názov.",
        "sl": "Takšna podplast že obstaja za\n[%1].\nNavedite drug ime.",
        "sq_al": "Një shtresë fëmijë e tillë ekziston tashmë për\n[%1].\nJu lutemi specifikoni një emër të ndryshëm.",
        "sr": "Таква детска слој већ постоји за\n[%1].\nМолим да наведете друго име.",
        "ta": "இந்த வகையான குழந்தை அடுக்கை ஏற்கனவே உள்ளது\n[%1] க்கு.\nதவிர்வுப் பெயரைக் கொடுக்கவும்.",
        "uk": "Така дочірня шар вже існує для\n[%1].\nБудь ласка, вкажіть інше ім'я.",
        "et": "Selline alakiht on juba olemas\n[%1].\nPalun määrake teine nimi.",
        "lv": "Šāda bērna slāņa jau eksistē\n[%1].\nLūdzu norādiet citu nosaukumu.",
    },
    "Such child layer already exist for \n[%1].\n": {
        "zh_cn": "此子图层已存在于\n[%1]中。\n",
        "zh_tw": "此子圖層已存在於\n[%1]中。\n",
        "de": "Ein solcher untergeordneter Layer existiert bereits für\n[%1].\n",
        "fr": "Un tel sous-calque existe déjà pour\n[%1].\n",
        "es": "Ya existe una subcapa como esta para\n[%1].\n",
        "ru": "Такой дочерний слой уже существует для\n[%1].\n",
        "ja": "このような子レイヤーはすでに存在します\n[%1]の場合。\n",
        "ko": "이러한 하위 레이어는 이미 존재합니다\n[%1]에 대해.\n",
        "it": "Un tale sottolayer esiste già per\n[%1].\n",
        "pt_pt": "Já existe uma subcamada como esta para\n[%1].\n",
        "nl": "Een dergelijke sublaag bestaat al voor\n[%1].\n",
        "pl": "Taki podlayer już istnieje dla\n[%1].\n",
        "hu": "Már létezik ilyen gyermekréteg a következőhöz:\n[%1].\n",
        "cs": "Taková podvrstva již existuje pro\n[%1].\n",
        "da": "En sådan underlag findes allerede for\n[%1].\n",
        "sv": "En sådan underlager finns redan för\n[%1].\n",
        "fi": "Sellainen alakerros on jo olemassa\n[%1].\n",
        "no": "En slik underlag eksisterer allerede for\n[%1].\n",
        "tr": "Böyle bir alt katman zaten var\n[%1].\n",
        "el": "Ένας τέτοιος υπο-επίπεδος υπάρχει ήδη για\n[%1].\n",
        "he": "� שכבה ילדה כזו כבר קיימת עבור\n[%1].\n",
        "id_id": "Lapisan anak seperti ini sudah ada untuk\n[%1].\n",
        "th": "ชั้นย่อยดังกล่าวมีอยู่แล้วสำหรับ\n[%1].\n",
        "ar": "هذه الطبقة الفرعية موجودة بالفعل ل\n[%1].\n",
        "ca": "Ja existeix una subcapa com aquesta per a\n[%1].\n",
        "eu": "Geroago geruza bat dagoeneko dago:\n[%1].\n",
        "gl": "Xa existe unha subcapa como esta para\n[%1].\n",
        "hi": "इस तरह की चाइल्ड लेयर पहले से मौजूद है\n[%1] के लिए।\n",
        "ka": "ასეთი ქ gyermek ფენა უკვე არსებობს\n[%1].-ზე.\n",
        "mk": "Таква детска слој веќе постои за\n[%1].\n",
        "pa": "ਇਸ ਤਰ੍ਹਾਂ ਦੀ ਚਾਈਲਡ ਲੇਅਰ ਪਹਿਲਾਂ ਹੀ ਮੌਜੂਦ ਹੈ\n[%1] ਲਈ।\n",
        "ro_ro": "Un astfel de sub-strat există deja pentru\n[%1].\n",
        "sk": "Takáto podvrstva už existuje pre\n[%1].\n",
        "sl": "Takšna podplast že obstaja za\n[%1].\n",
        "sq_al": "Një shtresë fëmijë e tillë ekziston tashmë për\n[%1].\n",
        "sr": "Таква детска слој већ постоји за\n[%1].\n",
        "ta": "இந்த வகையான குழந்தை அடுக்கை ஏற்கனவே உள்ளது\n[%1] க்கு.\n",
        "uk": "Така дочірня шар вже існує для\n[%1].\n",
        "et": "Selline alakiht on juba olemas\n[%1].\n",
        "lv": "Šāda bērna slāņa jau eksistē\n[%1].\n",
    },
}

def get_language_from_filename(filename):
    basename = os.path.basename(filename)
    if basename.startswith("librecad_"):
        lang = basename[9:-3]
    elif basename.startswith("plugins_"):
        lang = basename[8:-3]
    else:
        return None
    return lang.lower()

def get_translation(source, lang):
    if source not in TRANSLATIONS:
        return None
    if lang in TRANSLATIONS[source]:
        return TRANSLATIONS[source][lang]
    if lang in LANGUAGE_FALLBACKS:
        fallback = LANGUAGE_FALLBACKS[lang]
        if fallback in TRANSLATIONS[source]:
            return TRANSLATIONS[source][fallback]
    return None

def fix_unfinished_translations(ts_file):
    lang = get_language_from_filename(ts_file)
    if lang is None:
        return 0

    with open(ts_file, 'r', encoding='utf-8') as f:
        content = f.read()

    modified_count = 0

    for source in TRANSLATIONS.keys():
        target = get_translation(source, lang)
        if target is None:
            continue

        source_escaped = re.escape(source)
        pattern = rf'<source>{source_escaped}</source>\s*<translation type="unfinished">.*?</translation>'

        target_escaped = target.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;').replace('"', '&quot;').replace("'", '&apos;')
        replacement = f'<source>{source}</source>\n        <translation>{target_escaped}</translation>'
        new_content = re.sub(pattern, replacement, content, flags=re.DOTALL)
        if new_content != content:
            content = new_content
            modified_count += 1
            source_display = source.replace('\n', '\\n')[:50] + '...' if len(source) > 50 else source.replace('\n', '\\n')
            print(f"  Translated '{source_display}' to '{target_escaped[:50]}...'")

    if modified_count > 0:
        with open(ts_file, 'w', encoding='utf-8') as f:
            f.write(content)

    return modified_count

def main():
    ts_dirs = ['librecad/ts', 'plugins/ts']
    total_modified = 0
    total_files = 0

    for ts_dir in ts_dirs:
        print(f"\n=== Processing {ts_dir} ===")
        ts_files = sorted([f for f in os.listdir(ts_dir) if f.endswith('.ts')])
        total_files += len(ts_files)

        for i, ts_file in enumerate(ts_files, 1):
            ts_path = os.path.join(ts_dir, ts_file)
            print(f"[{i}/{len(ts_files)}] {ts_file}")

            modified = fix_unfinished_translations(ts_path)
            if modified > 0:
                total_modified += modified
                print(f"  Updated {modified} translation(s)")
            else:
                print(f"  No changes needed")

    print(f"\n=== Summary ===")
    print(f"Total files processed: {total_files}")
    print(f"Total translations updated: {total_modified}")

if __name__ == "__main__":
    main()
