.TH LIBRECAD 1 "December 2013" "LibreCAD"
.SH NAME
LIBRECAD \- A professional CAD System.
.SH DESCRIPTION
LibreCAD is a professional CAD System. With LibreCAD you can easily construct and
change drawings with ISO-texts and many other features and save them as
DXF-files. These DXF-files are the interface to many CAD-systems such as
AutoCAD(R) and many others.

LibreCAD has no special invocation parameters.

We are very sorry but could not include the manual because of License
issues with the manual from the original QCad CE edition. However, we
are working to create a new manual specifically for LibreCAD.

In the mean time, to get help on LibreCAD, please visit the following
link: https://librecad.org/

There are some wonderful people on the forum and IRC channel that can
give you a hand to get going.

We are sure you will enjoy LibreCAD as much as we do, even
without a manual.
