.TH LIBRECAD 1 "January 2010" "Debian GNU/Linux"
.SH NAME
LIBRECAD \- A professional CAD System.
.SH DESCRIPTION
LibreCAD is a professional CAD System. With LibreCAD you can easily construct and
change drawings with ISO-texts and many other features and save them as
DXF-files. These DXF-files are the interface to many CAD-systems such as
AutoCAD(R) and many others.

LibreCAD has no special invocation parameters. You can find the useful
docs in /usr/share/doc/librecad
